### ISSUE TITLE
demo error: error in building shared-object library from C snippets

### ISSUE THREAD

**Issue by yijunwang0805** [kingaa/pomp#100]
Hi,

Thank you so much for your wonderful package and beautifully written demo.

I am running the demo [here](https://kingaa.github.io/clim-dis/parest/parest.html#fitting-sir-to-an-epidemic-curve-using-likelihood).

While running the code
```R
pomp(
  data=subset(niamey,community=="A",select=-community),
  times="biweek",t0=0,
  skeleton=vectorfield(
    Csnippet("
             DS = -Beta*S*I/N;
             DI = Beta*S*I/N-gamma*I;
             DR = gamma*I;")),
  initializer=Csnippet("
                       S = S_0;
                       I = I_0;
                       R = N-S_0-I_0;"),
  statenames=c("S","I","R"),
  paramnames=c("Beta","gamma","N","S_0","I_0")) -> niameyA
```
I run into a problem,
```R
in ‘pomp’: the unrecognized argument ‘initializer’ is available for use by the POMP basic components.
Error: error in building shared-object library from C snippets: in ‘Cbuilder’: compilation error: cannot compile shared-object library ‘C:/Users/yijun/AppData/Local/Temp/RtmpG26XyR/13300/pomp_cef08ad7f96be175b03fccb73df6ffb6.dll’: status = 1
compiler messages:
Warning messages:
1: In system(cmd) : 'make' not found
2: In system(paste(cmd, "shlib-clean")) : 'make' not found
In addition: Warning message:
In system2(command = R.home("bin/R"), args = c("CMD", "SHLIB", "-c",  :
  running command '"C:/PROGRA~1/R/R-36~1.1/bin/R" PKG_CPPFLAGS="-IC:/Users/yijun/Documents/R/win-library/3.6/pomp/include -IC:/Users/yijun/Documents" CMD SHLIB -c -o C:/Users/yijun/AppData/Local/Temp/RtmpG26XyR/13300/pomp_cef08ad7f96be175b03fccb73df6ffb6.dll C:/Users/yijun/AppData/Local/Temp/RtmpG26XyR/13300/pomp_cef08ad7f96be175b03fccb73df6ffb6.c' had status 1
```

I notice the issue is similar to #83 but it is slightly different. #83's issue is with clang.

Would you please spend a couple of minutes helping me out?

Background: I am trying to write a SEIR model in python to forecast future infectious for COVID-19. But I don't know how to write the code for using markov chain monte carlo to estimate the parameter beta. I have look at the code [here](https://peerj.com/articles/cs-55/) but still could not figure out how to re-write the model specification for the SEIR model.

**Comment by kingaa** [comment]
- [FAQ 1.4](http://kingaa.github.io/pomp/FAQ.html#i-am-running-a-piece-of-pomp-code-i-found-on-the-web-but-i-get-errors.-what-is-going-on).
- [Issue 98](https://github.com/kingaa/pomp/issues/98).
- The materials you are following are dated May 2017.  There can be no guarantee that old materials will remain up to date!
