### ISSUE TITLE
Use matrix (compartment x time) of covariates

### ISSUE THREAD

**Issue by noamross** [kingaa/pomp#102]
Hello,  I am writing a model that simulates a series of `K` patches, each of which has an independent time series of covariates.  Right now am defining these with

```
covariate_table(
  covar_1 = ...,
  covar_2 = ...,
  ...,
  covar_K = ...,
   order = "constant",
  times = 1:t)
```

However, as `K` varies between experiments, I'd like to be able to refer to these covariates by _index_ in my `rprocess` Csnippet code.  Is there a way for me for me to refer to coviates as `covar[k]`? I suspect a `#define` macro might do it if there's a way to refer to the covariate object a whole.

**Comment by kingaa** [comment]
@noamross: Have a look at [FAQ 3.1](https://kingaa.github.io/pomp/FAQ.html#vector-in-csnippet) and let me know if you still have questions.

**Comment by noamross** [comment]
Thank you.  I'm afraid I'm still not clear on this.  Here's a minimal Csnippet simulator for variables (`X_1`, ..., `X_K`), a single parameter `beta` (as well as `n_patches`) and using the covariate table above.  I am trying to figure out if the covariates can be referred to by an index (`covar(1)` or `covar[1]`) rather than name(`covar_1`).

```
rSim <- Csnippet("
double *Xl  = &X_1;
int npatches = (int) n_patches;
#define X(K) X[(K)]
// Something here to be able to refer to covariate `covar_1` as covar(1)?
double dX;
  for (int k = 0; k < npatches, k++) {
    dX = beta * covar(k);
    X(k) += dX;
}
")
```

**Comment by noamross** [comment]
Aha, by examining the C code generated by pomp I believed I have answered by own question.  Covariates are stored in a table called `__covars` with indices `__covindex`.  I think that the above can be done by:

```
rSim <- Csnippet("
double *Xl  = &X_1;
int npatches = (int) n_patches;
#define X(K) X[(K)]
#define covar(K) (__covars[__covindex[K]])  // <-- This
double dX;
  for (int k = 0; k < npatches, k++) {
    dX = beta * covar(k);
    X(k) += dX;
}
")
```

Note that if there are other, non-patch-specific covariates, they will modify the index `K` used for lookup.

**Comment by kingaa** [comment]
Yes, you are onto it.  Good on you for using the Source.  Will you have problems given that your macro X is defined in terms of itself?

**Comment by noamross** [comment]
Will report back in a bit when when my real model is at MWE state, but I think that I'm OK here since `covar` != `covars`.

**Comment by noamross** [comment]
Ah, yes, that's right, it should be
```
#define X(K) Xl[(K)]
```

**Comment by kingaa** [comment]
@noamross: Is everything working now?  I am closing this issue, but feel free to reopen if there is more to discuss!
