### ISSUE TITLE
Question about the SIR example

### ISSUE THREAD

**Issue by Quenton1** [kingaa/pomp#105]
Hi, all. I'm trying to learn the example of "More model complexity: time-dependence, covariates, extra-demographic stochasticity"  of (https://kingaa.github.io/pomp/vignettes/oaxaca.html#more_model_complexity:_time-dependence,_covariates,_extra-demographic_stochasticity)

And I revise the code to fit the new version of pomp. This is my code.
```
rproc <- Csnippet("
                  double rate[6];
                  double dN[6];
                  double Beta;
                  double dW;

                  Beta = exp(b1 + b2 * cos(M_2PI * Phi) + b3 * sin(M_2PI * Phi));

                  rate[0] = births;                // birth
                  rate[1] = Beta * (I + iota) / P; // infection
                  rate[2] = mu;                    // death from S
                  rate[3] = gamma;                 // recovery
                  rate[4] = mu;                    // death from I
                  rate[5] = mu;                    // death from R

                  dN[0] = rpois(rate[0] * dt);
                  reulermultinom(2, S, &rate[1], dt, &dN[1]);
                  reulermultinom(2, I, &rate[3], dt, &dN[3]);
                  reulermultinom(1, R, &rate[5], dt, &dN[5]);
                  dW = rnorm(dt, sigma * sqrt(dt));
                  S += dN[0] - dN[1] - dN[2];
                  I += dN[1] - dN[3] - dN[4];
                  R += dN[3] - dN[5];
                  P = S + I + R;
                  Phi += dW;
                  H += dN[1];
                  noise+= (dW - dt) / sigma;
                  ")

## ----initializer---------------------------------------------------------
rinit <- Csnippet("
                  double sum = S_0 + I_0 + R_0;
                  S = nearbyint(popsize * S_0 / sum);
                  I = nearbyint(popsize * I_0 / sum);
                  R = nearbyint(popsize * R_0 / sum);
                  P = S + I + R;
                  H = 0;
                  Phi = 0;
                  noise = 0;
                  ")

## ----rmeasure------------------------------------------------------------
rmeas <- Csnippet("
                  cases = rnbinom_mu(theta, rho * H); 
                  ")


## ----dmeasure------------------------------------------------------------
dmeas <- Csnippet("
                  lik = dnbinom_mu(cases, theta, rho * H, give_log);
                  ")

case %>% 
  pomp(t0=0,
       time="time",
       rprocess=euler(step.fun=rproc,delta.t=1/52/20),
       rinit=rinit,
       dmeasure=dmeas,
       rmeasure=rmeas,
       covar=covariate_table(birth, times = "time"), 
       accumvars=c("H","noise"),              
       statenames=c("S","I","R","H","P","Phi","noise"),
       paramnames = c("gamma","mu","popsize", 'rho', 
                      "theta", "sigma", "b1", "b2", "b3","iota",
                      "S_0", "I_0", "R_0")
  ) -> m1



m1 %>%
  as.data.frame() %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x=time,y=value))+
  geom_line()+
  facet_grid(variable~.,scales="free_y")


##########code simulate#######################
params = c(popsize = 500000, iota = 5,
           b1 = 6, b2 = 0.2, b3 = -0.1,
           gamma = 26, mu = 1/50, rho = 0.1, theta = 100,
           sigma = 0.3, S_0 = 0.055, I_0 = 0.002, R_0 = 0.94)

simulate(m1,nsim=10,format="data.frame",params=params,include.data=FALSE) -> sims

library(ggplot2)
library(plyr)
ggplot(sims, 
       mapping=aes(x=time,y=cases,group=.id,color=.id=="data"))+
  geom_line()+
  guides(color=FALSE)+
  facet_wrap(~.id)
```

This is my data for testing.
```
time<-seq(0,10,by=1/52)
births<-600
birth<-data.frame(time,births)

cases<-10
case<-data.frame(time,cases)
```

And the code of simulation gives me this result.
![image](https://user-images.githubusercontent.com/62826630/78857103-13249a80-7a5b-11ea-81ff-e6364290fc89.png)
Rather than the result of cases in the website.
![image](https://user-images.githubusercontent.com/62826630/78857277-85957a80-7a5b-11ea-8663-44f5d761798f.png)
My result seems to get very high in the early stage and then no increase and not effect of seasonality at all.
But the example in the website has some fluctuation。

Do you have some ideas about what's wrong with my code?

Thanks for your help!

**Comment by kingaa** [comment]
@Quenton1: Don't have time to look at your code in great detail right now.  Some observations and suggestions to help you immediately.  We can communicate more later if these don't solve the problem.

1. The codes in that document have already been adapted to version 2 of **pomp**.  Are there revisions needed to bring it up to date with 2.7?
1. I don't understand what is the relationship of the lines of code following "This is my data for testing" to the rest of the codes or the plots.
1. A line-by-line `diff` of your code vs. the code in the R script accompanying the Oaxaca document would reveal specific differences that must be responsible.
1. A plot comparable to the one in the document would display not just the observable variable but also the state variables and covariates, which may make diagnosis much easier.

**Comment by kingaa** [comment]
@Quenton1, not having heard more from you, I'm closing this issue.  Feel free to re-open if there is more to discuss.
