### ISSUE TITLE
supply a string to rw.sd?

### ISSUE THREAD

**Issue by andreashandel** [kingaa/pomp#106]
Hi Aaron,
I'm finally (after years!) doing some serious pomping, together with John and others working on some COVID forecasting. As I dig through pomp, I stumble often, so far been able to get things figured out. But now I've got something I can't figure out. I want to feed a string to `rw.sd`. Basically instead of this:
```
x <- rw.sd( a = 0.1, S_0 = ivp(0.2))

I want this
s1 = "a = 0.1, S_0 = ivp(0.2)"
x <- rw.sd(s1)
```
Looking at Issue #33, I tried `x <- do.call(rw.sd,as.list(s1))` but that didn't work. Neither did some attempts at assigning the call slot in the object and similar. Is there a way to build `rw.sd` by feeding it a string?

Thanks!

**Comment by kingaa** [comment]
Yes, rw.sd is designed to take a set of expressions, that it then evaluates in a special environment.  It is not a normal function.  That is, it uses non-standard evaluation.

To answer your question literally, you might do something like:
```
s1 <- "rw.sd(a=0.1,S_0=ivp(0.2))"
eval(parse(text=s1))
```

However, I suspect that you are making things more complicated than they need to be.  What are you trying to accomplish?

**Comment by andreashandel** [comment]
Thanks that worked! I'm trying to not hard-code a fairly big rw.sd object but instead build it more automatically by combining from a vector of parameters and perturbation values.

**Comment by kingaa** [comment]
Ah, I see.  I'll close this issue now, but feel free to re-open it if needed.
