### ISSUE TITLE
pmcmc example for SIR model in pomp version 2

### ISSUE THREAD

**Issue by NedaJalali-codes** [kingaa/pomp#108]
Would you please provide an example of the "pmcmc" for a SIR model in the "pmcmc" R documentation?

**Comment by kingaa** [comment]
@NedaJalali-codes: I will add this to the to-do list.  However, priorities at the moment being what they are, I doubt I will get to this within the next several months.  If you'd like to take a stab at it yourself, we are always accepting contributions!

**Comment by NedaJalali-codes** [comment]
Thanks for your response. The reason that I was looking for an example is that when I trying to run "pmcmc" I got this error:
```‘dmeasure’ returns illegal value.```
So I wanted to check my codes with an example to see where I made a mistake.

**Comment by kingaa** [comment]
@NedaJalali-codes: have a look at [FAQ 4.1](http://kingaa.github.io/pomp/FAQ.html#illegal-dmeasure).  If you can't resolve the issue by following that advice, be sure to read [FAQ 1.1](http://kingaa.github.io/pomp/FAQ.html#effective-request) before re-opening this issue, or opening a new one!  Thanks!

**Comment by GreyPEK** [comment]
Hi, if now there are any cases of using mcmc or pmcmc to estimate parameters of SIR model? I did not find it in the documentation.[https://kingaa.github.io/pomp/docs.html](url)
Thanks!
