### ISSUE TITLE
fragility of reulermultinom?

### ISSUE THREAD

**Issue by bbolker** [kingaa/pomp#110]
I'm working on figuring this out for myself, but in the meanwhile: `reulermultinom` seems to have an issue with very small probabilities and large states.  This seems to work in naive R (so it's not simply a problem of floating-point limits) ...

(Just curious: why is the pomp repository so big?  I'm at 400 MB downloaded and 15% of the way through ... ??)

```
## hand-rolled version of reulermultinom
myEM <- function(n, size, rate, dt) {
    S  <- sum(rate)
    p0 <- (1-exp(-S*dt))
    p  <- c(1-p0,p0*rate/S)
    return(rmultinom(n,size=size, prob=p)[-1,,drop=FALSE])
}

## checking hand-rolled version vs pomp version
set.seed(101)
pomp_res <- pomp::reulermultinom(100,size=10000,rate=c(a=1,b=2,c=3),dt=0.1)
set.seed(101)
my_res <- myEM(100,size=10000,rate=c(a=1,b=2,c=3),dt=0.1)
all.equal(pomp_res,my_res)  ## TRUE

## dump(c("s0","M"))
source("dumpdata.txt")
i <- 1
pomp::reulermultinom(n=1,size=s0[[1]],rate=M[i,-i],dt=1) ## all NaN
myEM(n=1,size=s0[[1]],rate=M[i,-i],dt=1)  ## sensible
```

[dumpdata.txt](https://github.com/kingaa/pomp/files/4505430/dumpdata.txt)

**Comment by bbolker** [comment]
Oops.  State was non-integer but so big that I didn't notice. Sorry.  (Also, the repo is "only" 768 M or so)

**Comment by kingaa** [comment]
@bbolker: Was in the process of replying.  Yes, non-integer `size` is the problem.  Wonder why **R** doesn't have the same problem, or rather, why `rbinom` does but `rmultinom` does not:
```
> rbinom(n=1,size=3.5,prob=0.2)
[1] NA
Warning message:
In rbinom(n = 1, size = 3.5, prob = 0.2) : NAs produced
> rmultinom(n=1,size=3.5,prob=c(0.2,0.8))
     [,1]
[1,]    1
[2,]    2
```
It does add a degree of fragility: why is it there?  Thoughts?

768 MB = lots of history and very thorough testing!
