### ISSUE TITLE
Introducing a time lag in dmeasure or rmeasure functions

### ISSUE THREAD

**Issue by jdlee** [kingaa/pomp#112]
I would like to model the observations of the process as a noisy and delayed estimate of the state. It seems like it might be possible to create a measurement model that links the data to a lagged unobserved state, but I could not find any examples of how this might be done.

Here is code that I would like to use to set "obs" equal to a lagged instance of `Y`, something like `Y[t-1]`.  Any suggestions or pointers to examples would be greatly appreciated.
```
 rmeasure = function (Y, t_sd, ...) {
    obs = rnorm(n = 1, mean = Y, sd = t_sd)
    obs = c(obs = obs)
}
```

**Comment by kingaa** [comment]
@jdlee: your request is a bit problematic.  In particular, for **pomp**'s inference algorithms to be mathematically valid, they must respect the structure of a POMP model.  In particular, there are certain relationships of conditional independence among the model variables that are assumed to hold.  These are diagrammed [here](https://kingaa.github.io/sbied/intro/intro.html#another-pomp-model-schematic), for example.

Among these relationships is the conditional independence of `Y[t1]` and `Y[t2]` given `X[t1]`, for all `t1` and `t2`.  (Here, as usual, I use `Y` for the vector of observables and `X` for the vector of latent state variables.  The **pomp** software effectively enforces this constraint by giving the user access to only one `Y[t]` at any time.

That said, it is actually the case that some of the algorithms (e.g., all particle-filter-based algorithms) are valid if the distribution of `Y[t]` depends not only on `X[t]` but also on `Y[s]` for `s < t`.  As I say, the software was not designed to handle this case.  However, there is a simple workaround.  **pomp** can accommodate multivariate observations.  In particular, nothing stops you from introducing lagged observations as new data variables.

For example, suppose I have a data frame, `dat`, containing the variables `t` and `y`, representing time and some observable, respectively.  Then the following will create two new variables, containing the lagged observations.
```
library(tidyverse)
dat %>% mutate(y1 = lag(y,1), y2 = lag(y,2)) -> dat
```
I could simply pass `dat` to any of **pomp**'s functions and refer, in my dmeasure and/or rmeasure basic model components, not only to `y`, `t`, the parameters, and the latent state variables, but also to `y1` and `y2`.

**Comment by kingaa** [comment]
@jdlee: Not sure what is happening with your issue.  I am closing it for now, but feel free to reopen if more discussion is needed.
