### ISSUE TITLE
File handling and access of (multidimensional) arrays within Csnippets

### ISSUE THREAD

**Issue by christelpei** [kingaa/pomp#12]
Is it possible to read data from file in the Csnippets, in particular for initialization or parameter choice – and how do I mask quotation marks in the file handles?
Is it otherwise possible to read a parameter matrix (e.g. a contact matrix) within in R and use it within the Csnippets (and how do I deal with the different offset in array indices starting from 0 or 1 in C and R, respectively)?

**Comment by kingaa** [comment]
See the response to Issue #11.
