### ISSUE TITLE
Warning ：install.packages("panelPomp")   

### ISSUE THREAD

**Issue by AWalkInClouds** [kingaa/pomp#127]
I tried to  install.packages("panelPomp")  and I got this warning:
    Warning in install.packages :
  package ‘panelPomp’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

R version 4.0.3 (2020-10-10)
pomp  version 3.1
macOS Catalina  version 10.15.5

Thank you!

**Comment by kingaa** [comment]
Not sure what you're asking.  **pomp** provides a suite of low-level tools for inference.  You can use these to sample from the posterior, and then simulate the process.  What more do you want?

**Comment by AWalkInClouds** [comment]
See that example ?  How to install a suite of low-level tools？

**Comment by kingaa** [comment]
Please don't change the topic of an issue: it is confusing.  It is better to close the issue and open a new one.

**Comment by kingaa** [comment]
As for your trouble installing **panelPomp**, why not bring that up on the **panelPomp** site?  I am not the maintainer of that package.  The error you are getting is because that package is not available on CRAN.  It is available elsewhere.
