### ISSUE TITLE
more detail on delays in blowflies1 and blowflies2?

### ISSUE THREAD

**Issue by slwu89** [kingaa/pomp#129]
I'm interested in implementing models with delays, as was shown in the blowflies example(s): https://github.com/kingaa/pomp/blob/aaaf7413c4362734d667a11220be1ceda91affd7/R/blowflies.R#L95

This method only works for `discrete_time` models? Is there any way to model delays for `euler` based process models? Is there an official method to incorporate delays?

**Comment by kingaa** [comment]
As the name implies, **pomp** assumes Markovian structure.  In particular, the latent state process must be Markov.  Of course, this is not necessarily incompatible with dependence on delayed variables.  If one can use the usual tricks to enfold the delayed variables into the state, one can make a Markov process out of one that has delays.  In the discrete-time case, this is particularly easy.  It can also be accomplished in continuous time if the delayed variables enter via a Gamma-shaped kernel, i.e., using the linear chain trick.  These two tricks can be used to make better or worse approximations to many systems with delays.  Beyond this, **pomp** does not go.

**Comment by slwu89** [comment]
Thanks for the explanation @kingaa, I also looked through the closed issues and saw someone asking about a lag-2 Markov chain. I think this is good to close!
