### ISSUE TITLE
debugging statements in Csnippets?

### ISSUE THREAD

**Issue by bbolker** [kingaa/pomp#131]
I'm trying to help out [this person on StackOverflow](https://stackoverflow.com/questions/65554258/r-function-loglik-returning-inf/65555154#65555154), and am curious (it's not really burning, I think they can diagnose/solve their problem without it) how/whether it's possible to put a `printf` or `Rprintf` (or some equivalent) within a Csnippet?

In the meantime, for debugging purposes they can use an R function rather than a Csnippet.  But it does seem like something it would be good to know how to do ...

(happy New Year!)

**Comment by kingaa** [comment]
Hi Ben! Good to hear from you! Happy 2021 to you too! 

It's as straightforward as can be to put an `Rprintf` into a C snippet.  The snippets are just embedded into a file according to a template and then compiled via `R CMD SHLIB` and linked.  So any part of **R**'s [C API](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-R-API) is available.  There is at least one [example in Issue 13](https://github.com/kingaa/pomp/issues/13) (not that you would find that easily).  I will add an FAQ entry on this topic.

**Comment by kingaa** [comment]
Added [FAQ 7.1](https://kingaa.github.io/pomp/FAQ.html#debug-c-snippets).  Comments/suggestions very welcome.

**Comment by bbolker** [comment]
Yeah, I did try `Rprintf` , but I forgot to put in a newline, so the code seemed to hang ... ? (Because something about output buffering ...)

**Comment by kingaa** [comment]
Interesting.  That's never happened to me.  To get a MWE, would I just leave off the newline?

**Comment by bbolker** [comment]
Seems to be a bad interaction with emacs. Run with `R CMD BATCH --vanilla`, this does fine.

```
library(tidyverse)
library(pomp)
options(stringsAsFactors=FALSE)
stopifnot(packageVersion("pomp")>="3.0")
set.seed(1350254336)

library(tidyverse)
library(pomp)

sir_step <- Csnippet("
double dN_SI = rbinom(S,1-exp(-Beta*I/N*dt));
double dN_IR = rbinom(I,1-exp(-mu_IR*dt));
S -= dN_SI;
I += dN_SI - dN_IR;
R += dN_IR;
H += dN_IR;
")

sir_init <- Csnippet("
S = nearbyint(eta*N);
I = 1;
R = nearbyint((1-eta)*N);
H = 0;
")

dmeas <- Csnippet("
      double ll = dbinom(reports,H,rho,give_log);
      lik =  (!isfinite(ll) ? -1000 : ll );
")

dmeas  <- function(reports,H,rho,log, ...) {
    lik <- dbinom(reports,size=H,prob=rho,log=log)
    if (!is.finite(lik)) {
        lik <- -1000
        browser()
    }
    return(lik)
}

dmeas <- Csnippet("
      lik = dbinom(reports,H,rho,give_log);
      if (!isfinite(lik)) {
             /*  Rprintf(\"bad\\n\"); */
             Rprintf(\"bad\");
             lik = -1000;
      }
")

        

rmeas <- Csnippet("
reports = rbinom(H,rho);
")

in_data <- read_csv("https://kingaa.github.io/sbied/pfilter/Measles_Consett_1948.csv") %>%
  select(week,reports=cases) %>%
    filter(week<=42)


measSIR <- pomp(
    in_data,
    times="week",
    t0=0,
    rprocess=euler(sir_step,delta.t=1/7),
    rinit=sir_init,
    rmeasure=rmeas,
    dmeasure=dmeas,
    accumvars="H",
    statenames=c("S","I","R","H"),
    paramnames=c("Beta","mu_IR","eta","rho","N"),
    params=c(Beta=100,mu_IR=0.5,rho=0.5,eta=0.06,N=38000)
  ) -> measSIR

measSIR %>%
  pfilter(Np=5000) -> pf
logLik(pf)
```

**Comment by kingaa** [comment]
Yeah, could be.  I just did the following in a standalone **R** session, and it runs fine.  In an ESS session, however, it seems to cause emacs trouble (the extra layer of buffering, maybe?).

```
library(pomp)
sir() %>%
  simulate(dmeasure=Csnippet("
    lik = dbinom(reports,cases,rho,give_log);
    Rprintf(\"%lg %lg %lg\",reports,cases,rho);"
  ),
  paramnames=c("rho"),
  statenames=c("cases")
  ) -> x
pfilter(x,Np=1000)
```

**Comment by kingaa** [comment]
BTW, it's good advice to the StackOverflow poster to avoid the workaround in things like
```
 lik =  (!isfinite(ll) ? -1000 : ll );
```
The **pomp** codes know how to handle the likelihood = 0 case correctly.  So trapping this just hides the actual problem, which is that the model is incompatible with the data.
