### ISSUE TITLE
error, 'simulate' function 

### ISSUE THREAD

**Issue by ksm5k** [kingaa/pomp#133]
```
covidSEIRSR %>%
  simulate(
    nsim=20,format="data.frame",include.data=TRUE
  ) -> sims
```

is what I run. 

I receive the following error:
```
Error: in ‘simulate’: argument "n" is missing, with no default
```

I ran `? simulate` and looked at the documentation, and I do not see this argument listed. I don't have any variables `n` in my earlier code. 

What should I do?

**Comment by kingaa** [comment]
Do you have a parameter called `n`?

If you need more help, you’ll have to follow FAQ 1.1.

**Comment by kingaa** [comment]
I am closing this issue.  Please reopen if necessary.
