### ISSUE TITLE
resampling frequency

### ISSUE THREAD

**Issue by umbertopicchini** [kingaa/pomp#18]
Hi
in the documentation it is clearly stated that the currently implemented particle filter resamples particles at each time point. I was wondering if there exist an experimental version of pomp (e.g. a version intended for future release) that allow users to control the resampling frequency, e.g. resample only when the ESS goes below a certain threshold.

**Comment by kingaa** [comment]
Such an experimental version does not exist, but I'd welcome contributions in such a direction.  The codes that would need to be modified are quite compact, mostly contained in the 'pfilter.c' file and in 'pfilter.R'.  Would you be interested in contributing?

**Comment by umbertopicchini** [comment]
Thanks, but (sadly) I am not a C nor R programmer
