### ISSUE TITLE
Demo(sir) don't work

### ISSUE THREAD

**Issue by Spatial-R** [kingaa/pomp#2]
The **demo(sir)** cann't work well in my compute. Error messages are: 

Error in (function (name = NULL, dir = NULL, statenames, paramnames, covarnames,  : 
    cannot compile shared-object library        ‘C:/Users/dell/AppData/Local/Temp/RtmpSEv0Pr/pompB0D5B1C24832.dll’
     In addition: Warning message:
     running command '"D:/R-3.2.1/bin/R" PKG_CFLAGS=" -ID:/R-3.2.1/library/pomp/include" CMD     SHLIB -o C:/Users/dell/AppData/Local/Temp/RtmpSEv0Pr/pompB0D5B1C24832.dll   C:/Users/dell/AppData/Local/Temp/RtmpSEv0Pr/pompB0D5B1C24832.c' had status 1 
Error: in ‘pomp’: error in building shared-object library from Csnippets:
 Error in (function (name = NULL, dir = NULL, statenames, paramnames, covarnames,  : 
     cannot compile shared-object library     ‘C:/Users/dell/AppData/Local/Temp/RtmpSEv0Pr/pompB0D5B1C24832.dll’

Session information for my compute is as followed:

```
 R version 3.2.1 (2015-06-18)
 Platform: x86_64-w64-mingw32/x64 (64-bit)
 Running under: Windows 8 x64 (build 9200)
locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base     

 other attached packages:
 [1] pomp_0.70-1

 loaded via a namespace (and not attached):
 [1] deSolve_1.12    subplex_1.1-4   tools_3.2.1     coda_0.17-1     mvtnorm_1.0-2  
 [6] grid_3.2.1      nloptr_1.0.4    lattice_0.20-31
```

**Comment by kingaa** [comment]
You are running `pomp` under Windows.  Have you installed [Rtools](http://cran.r-project.org/bin/windows/Rtools) as mentioned in the installation instructions?

**Comment by Spatial-R** [comment]
Yes, Rtools have been installed successfully!

**Comment by kingaa** [comment]
And you still have the error?

**Comment by Spatial-R** [comment]
YES. The **demo(rw2)** work well, however, the **demo(sir)** don't work!

**Comment by kingaa** [comment]
Please try the test code below and send me the results.

cat("#include <R.h>
     void hello (void) {
     Rprintf(\"hello world!\n\");
     }",
    file="hello.c")
system("R CMD SHLIB hello.c")
dyn.load(paste0("hello",.Platform$dynlib.ext))
.C("hello",PACKAGE="hello")

On Wed, Jul 8, 2015 at 9:02 AM, Bing Zhang notifications@github.com wrote:

> YES. The _demo(rw2)_ work well, however, the _demo(sir)_ don't work!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kingaa/pomp/issues/2#issuecomment-119570824.

## 

Aaron A. King, Ph.D.
Ecology & Evolutionary Biology
Mathematics
Center for the Study of Complex Systems
University of Michigan
GPG Public Key: 0x15780975

**Comment by kingaa** [comment]
To run the sir demo, one needs the ability to compile C code and dynamically link it to an R session.  See the installation instructions on the package website.

**Comment by Spatial-R** [comment]
I have solved the problem by reinstalled the Rtools and make sure  that the path was added correctly. In the process of installing Rtools, it will promt whether to add the path automaticly. Thanks Kingaa!
