### ISSUE TITLE
How to estimate parameters of SIR model

### ISSUE THREAD

**Issue by GreyPEK** [kingaa/pomp#204]
Sorry, I have not found relevant cases introducing SIR Model or other model parameters estimation, I wonder if you could provide an example? Thanks!

**Comment by kingaa** [comment]
Have you read any of the [documentation](https://kingaa.github.io/pomp/docs.html)?  Or read the [FAQ](https://kingaa.github.io/pomp/FAQ.html).

**Comment by GreyPEK** [comment]
I am so sorry to bother you! I did not find these before, just read the published article and the R package introduction file. Thanks!
