### ISSUE TITLE
zeronames functionality

### ISSUE THREAD

**Issue by christelpei** [kingaa/pomp#21]
I find the zeronames argument of pomp very helpful, but I needed a little trial and error to find out how it works exactly:
From the documentation it was not immediately clear to me whether "setting to zero after each observation" refers to the time points given in the time series data frame or the simulation step (delta.t, dt). Given the former, it might be worthwhile to warn users of "missing values", i.e. for reasonable results a time series of incidences needs to be equidistant  and if a data point is missing the simulation will suggest a doubled incidence.
A more tricky situation arises if the simulation is started at a time point t0 that lies more than the typical time interval in the time series before the first observation in the time series - which I would like to do for the dynamics to equilibrate before I do inference. This results in a situation in which the simulated variable has accumulated a much larger value than expected and observed. Is there an elegant way to fix this issue, i.e. to tell pomp how to evalutate the variable corresponding to the time series at the first data point?

**Comment by kingaa** [comment]
Thanks for the excellent feedback.  You put your finger on what has long been a point of confusion for beginning pompistas.  However, you should know that the treatment of accumulator variables in **pomp**   is correct even if the observations are not uniformly spaced in time.

Your point about surprising effects associated with `t0` when using accumulator variables is also a good one.  If one wishes to initialize the model at a `t0` which is well before the first observation, and one's observations are increments of an accumulator variable (e.g., disease incidence), then one can add a missing observation.  For example, suppose one has weekly incidence data, beginning on 1 Jan 2000 but one want to initialize the model 10 years previously.  One can set `t0` to 1 Jan 1990 and introduce an "observation" of a missing value (NA) at 25 Dec 1999.

Since you've been grappling with this recently, perhaps it wouldn't be hard for you to cobble up just a few lines of code to illustrate this?  It could go on the "pimp my pomp" page, or in the FAQ....  I'd be grateful for the assistance!

**Comment by christelpei** [comment]
Thanks for this helpful advice and the encouragement that I am not alone with my confusion. I indeed found out that the accumulator variables collect all data between two observation points. However, In case of missing data in a time series, this is usually not what you want to compare to. Typically a data point is just missing, for example in a time series of yearly incidences a missing data point will unlikely result in an incidence accumulated over two years in the next data point. So, I find the advice to mark missing values by NA really helpful - also for an early initialization well before t0.

Regarding code, I have tried to boil the problem down with code based on your example that I will gladly provide. Although it seems that I can edit the "pimp my pomp" page I would like you to decide how to put it there.

```
## Model adapted from http://kingaa.github.io/sbied/stochsim/stochsim.html 
## ----prelims,echo=F,cache=F---------------------------------------------------
set.seed(594709947L)
library(plyr)
library(reshape2)
library(pomp)
library(ggplot2)
require(magrittr)

## ----flu-data1----------------------------------------------------------------
read.table("http://kingaa.github.io/sbied/stochsim/bsflu_data.txt") -> bsflu
head(bsflu)

## -flu-data adapted from http://kingaa.github.io/sbied/stochsim/stochsim.html--
## NA values added
read.csv(text="
B,day
NA,   0 
1,   1
6,   2
26,  3
73,  4
NA,  5
293, 6
258, 7
236, 8
191, 9
124,10
69, 11
26, 12
11, 13
4,  14
")->bsflu_na

## ----plot data----------------------------------------------------------------
bsflu_melt <-melt(bsflu_na, id.var='day')
bsflu_melt <-na.omit(bsflu_melt)
ggplot(data=bsflu_melt, aes(x=day, y=value, color=variable)) + 
  geom_line() + geom_point()
## ----rproc2-------------------------------------------------------------------
sir_step <- Csnippet("
  double dN_SI = rbinom(S,1-exp(-Beta*I/N*dt));
  double dN_IR = rbinom(I,1-exp(-gamma*dt));
  S -= dN_SI;
  I += dN_SI - dN_IR;
  R += dN_IR;
  H += dN_IR;
  //Output for debugging
  Rprintf(\"  %f \\t %f \\n  \",I,H);
")

sir_init <- Csnippet("
  S = N-1;
  I = 1;
  R = 0;
  H = 0;
")

## ----meas-model---------------------------------------------------------------
dmeas <- Csnippet("lik = dbinom(B,H,rho,give_log);")
rmeas <- Csnippet("B = rbinom(H,rho);")



##-----------model without NA points--------------------------------------------
pomp(bsflu,time="day",t0=-8,rprocess=euler.sim(sir_step,delta.t=1/12),initializer=sir_init, rmeasure=rmeas,dmeasure=dmeas,
     zeronames="H",paramnames=c("Beta","gamma","N", "rho"),statenames=c("S","I","R","H")) -> sir

sims <- simulate(sir,params=c(Beta=1.5,gamma=1,rho=0.9,N=2600),
                 nsim=15,as=TRUE,include=TRUE)

##-------------plot ------------------------------------------------------------                 
                  sims %>%
  melt(id=c("sim","time")) %>%
  ggplot(aes(x=time,group=sim,color=sim,y=value))+
  geom_line()+
  facet_wrap(~variable,scales="free_y")


##-----------model with NA points-----------------------------------------------
pomp(bsflu_na,time="day",t0=-8,rprocess=euler.sim(sir_step,delta.t=1/12),initializer=sir_init, rmeasure=rmeas,dmeasure=dmeas,
     zeronames="H",paramnames=c("Beta","gamma","N", "rho"),statenames=c("S","I","R","H")) -> sir_na


## -----------------------------------------------------------------------------
sims_na <- simulate(sir_na,params=c(Beta=1.5,gamma=1,rho=0.9,N=2600),
                 nsim=15,as=TRUE,include=TRUE)


##-------------plot including NA data point at 0--------------------------------                 
                  sims_na %>%
  melt(id=c("sim","time")) %>%
  ggplot(aes(x=time,group=sim,color=sim,y=value))+
  geom_line()+
  facet_wrap(~variable,scales="free_y")

##------------plot with skipped NA data point at 0---------------------------------                
  sims_na %>%
  subset(time>"0")%>%
  melt(id=c("sim","time")) %>%
  ggplot(aes(x=time,group=sim,color=sim,y=value))+
  geom_line()+
  facet_wrap(~variable,scales="free_y")               




```

Maybe a FAQ on debugging might also be helfpul - it took me a while to sort out that I need to have \\n (double backslash) for a newline (while  \t (single backslash) and \\t (double backslash) work both, see above). Or is there a more elegant way of debugging than the occasional fprintf?

**Comment by kingaa** [comment]
This looks great and I can tweak it a bit here and there.  Shall we try writing a few blurbs for the "Pimp my pomp" page?  I suggest we add three sections:
1. How to handle missing data?  In addition to illustrating the use of NAs in the data, we should point out that the proper likelihood to associate with missing data is 1.
2. How to deal with accumulator variables and `t0` much less than `t[1]`.
3. How to include `Rprintf` statements inside of Csnippets for debugging purposes.  [Note that I've modified your original codes above to use `Rprintf` rather than C stdio.

What do you think?

**Comment by christelpei** [comment]
Sounds great - although I feel not exactly like an expert...

I could start writing No. 1 but would like to hand over to you for the discussion on the proper likelihood as this goes deeper into the implementation of pomp that I hardly know in its full depth.

No. 2 is included in the above and I will be happy to write a suggestion.

I could also recycle code from above for No. 3, though I am not sure about the pros & cons of Rprintf vs. (f)printf. Is this the place to look for it?
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Printing

**Comment by christelpei** [comment]
O.k. I will start writing some bits and pieces during this week - ideally including another issue: Is there a way to tell "simulate" to return a data frame with simulation results beyond the time frame given by time series (data), i.e. before t1 and after the last time point of observation for extrapolation (except for adding NAs?)

**Comment by kingaa** [comment]
Great, thanks!

> Is there a way to tell "simulate" to return a data frame with simulation results beyond the time frame given by time series (data)...?

Sure, just specify the desired times in the `times` argument to `simulate`.

**Comment by christelpei** [comment]
I have tried a few things in filling the times argument of simulate that I thought might be reasonable form the package manual (though without success)...apparently it is just:

```
simulate(pomp-object,..., times=c(1995:2050) ,...)
```

for simulation of the years 1995-2050 (with t0<=1995)?! Proves the value of an easy example!

**Comment by christelpei** [comment]
I have added a few bits and pieces on the ""Pimp my pomp" page but would leave the discussion of the proper use of likelihoods within pomp to you...Also strangely the links within the page do not seem to work.

**Comment by kingaa** [comment]
Thanks!  That really got the ball rolling.  I've edited your two new sections quite a bit.  What do you think?  Would these have answered your question at the beginning?  Could they be clearer?  More complete?

**Comment by kingaa** [comment]
Any comments on my edits of your wiki page?  If not, I'd like to close this issue and move the wiki material to the FAQ....

**Comment by christelpei** [comment]
Thanks for the new wiki page (and sorry for the delay on my side - after some travelling I am now back to pomp) - that would have helped me in the beginning and made me aware of some issues I was ignoring in the absence of error messages...
- it is helpful to see, that the likelhood has to explicitly take care of missing values, however, where is the "ISNA-function" defined? 
- I would skip this line "subset(select=-cond.loglik) %>%" in the code, as it is instructive to also see the log-likelihood
- add "library(plyr)", otherwise "arrange" will not work
  For me this issue is resolved! Thanks! :-)

**Comment by kingaa** [comment]
Thanks for this.  You have been very helpful!
- it is helpful to see, that the likelhood has to explicitly take care of missing values, however, where is the "ISNA-function" defined? 

> this is defined in the R headers.  I will mention this.
- I would skip this line "subset(select=-cond.loglik) %>%" in the code, as it is instructive to also see the log-likelihood

> Good idea.
- add "library(plyr)", otherwise "arrange" will not work

> Thanks!
