### ISSUE TITLE
pmcmc function could return Nan Nan Nan value for SIR model using the pomp

### ISSUE THREAD

**Issue by njuxcui** [kingaa/pomp#22]
I am using SIR model by the pomp. Former, I found the the pomp very useful. But these days, after I update my R studio, I am facing some problem for  "task 2 failed - "in ‘pmcmc’: error in ‘pfilter’: Error : in ‘pfilter’: ‘dmeasure’ returns non-finite value."(The weird thing is that sometime it could work out, but sometime it could not work out. But I used the same code.) So I add the print part to the dmeasure, and found that sometime, the pomp could get nan nan nan value for the S, I, R, some times not. How could that happen? Is that a bug? I linked my code below, it is almost the same code as on the paper: Statistical Inference for Partially Observed Markov Processes via the R Package pomp(in section 5).

```
library(pomp)
library(foreach)
rmeas<-"
cases=rnbinom_mu(theta,rho*I);
"
dmeas<-"
lik=dnbinom_mu(cases,theta,rho*I,give_log);
if (!R_FINITE(lik)) 
  Rprintf(\"%lg %lg %lg %lg %lg %lg\\n\",cases,theta,rho,S,I,R);
"

sir.step<-"
double rate[2];
double dN[2];
rate[0]=be*I;
rate[1]=mu;
reulermultinom(1,S,&rate[0],dt,&dN[0]);
reulermultinom(1,I,&rate[1],dt,&dN[1]);
S+=-dN[0];
I+=dN[0]-dN[1];
R+=dN[1];
"
sir<-pomp(data=data.frame(cases=NA,time=seq(1,14,by=1/2)),
          times="time",t0=-1/4,dmeasure=Csnippet(dmeas),
          rmeasure=Csnippet(rmeas),rprocess=euler.sim(
            step.fun=Csnippet(sir.step),delta.t=1/14/4),
          statenames=c("S","I","R"),
          paramnames=c("popsize","be","mu","rho","theta","S.0","I.0","R.0"),
          initializer=function(params,t0,...){
            fracs<-params[c("S.0","I.0","R.0")]
            setNames(c(round(params["popsize"]*fracs/sum(fracs))),c("S","I","R"))
          },params=c(popsize=769,be=0.002,mu=0.5,theta=500,rho=0.7,S.0=0.98,I.0=0.01,R.0=0.01))

sir<-simulate(sir,seed=190L)
plot(sir,type="p")
sir.log.tf<-function(params, ...) log(params)
sir.exp.tf<-function(params, ...) exp(params)
sir<-pomp(sir,toEstimationScale=sir.log.tf,fromEstimationScale=sir.exp.tf)
estpars<-c("be","mu","rho","S.0","I.0","R.0")
theta.true<-coef(sir)
mif1<-foreach(i =1:2,.combine = c)%dopar%{
  theta.guess<-theta.true
  theta.guess[estpars]<-rlnorm(n=length(estpars),
                               meanlog=log(theta.guess[estpars]),sdlog=1)
  mif(sir,Nmif=100,start=theta.guess, transform=TRUE,
      Np=2000,var.factor=2,cooling.fraction=0.7,
      rw.sd=c(be=0.02,mu=0.02,rho=0.02,S.0=0.02,I.0=0.02,R.0=0.02))
}
pf1<-foreach(mf=mif1,.combine=c) %dopar% {
  pf<-replicate(n=2,logLik(pfilter(mf,Np=10000)))
  logmeanexp(pf)
}
mf1<-mif1[[which.max(pf1)]]
theta.mif<-coef(mf1)
hyperparams<-list(min=coef(sir)/10,max=coef(sir)*10)
sir.dprior<-function(params, ...,log){
  f<-sum(dunif(params,min=hyperparams$min,max=hyperparams$max,
               log=TRUE))
  if(log) f else exp(f)
}

pmcmc1<-foreach(i=1:3,.combine=c) %dopar%{
  pmcmc(pomp(sir,dprior=sir.dprior),start=theta.mif,Nmcmc=20000,Np=100,max.fail=Inf,
        proposal=mvn.diag.rw(c(be=0.01,mu=0.01,rho=0.01,S.0=0.01,I.0=0.01,R.0=0.01)))
}
```

You could see that in the dmeas function, I print all of the parameter and when the error occurs, I could get the output:

```
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
27 500 0.842667 nan nan nan
```

Is that a bug? Or there is some problem in my code?

**Comment by kingaa** [comment]
Have you looked to see what is becoming of the parameters during your MCMC chain?  If some parameters that are assumed positive are actually being proposed to be negative, could this account for your problem?

**Comment by njuxcui** [comment]
I found that some parameters that are assumed positive , but actually being proposed to be negative.

```
1 0.217814 1 0.379755 0.00145209 0.379755 108 150 505
1 0.217814 1 0.379755 0.00145209 0.379755 107 150 506
1 0.217814 0 0.379755 0.00145209 0.379755 106 150 507
3 0.219266 1 0.379755 0.00145209 0.379755 105 151 507
0 0.22217 1 0.379755 0.00145209 0.379755 102 153 508
nan -0.0155832 0 0.387683 -0.0038958 0.387683 756 4 3
nan nan nan 0.387683 -0.0038958 0.387683 nan nan 3
nan nan nan 0.387683 -0.0038958 0.387683 nan nan nan
nan nan nan 0.387683 -0.0038958 0.387683 nan nan nan
nan nan nan 0.387683 -0.0038958 0.387683 nan nan nan
nan nan nan 0.387683 -0.0038958 0.387683 nan nan nan
```

You could see in the output of the rprocess in the pomp during the pmcmc, after one step, the parameter that is assumed to be positive becomes negative. But that is quite weird, you could see that in the above code, I did the transformation(log and exp as the inverse). This should make sure that the parameters are positive. In my code, this part I write as

```
sir.log.tf<-function(params, ...) log(params)
sir.exp.tf<-function(params, ...) exp(params)
sir<-pomp(sir,toEstimationScale=sir.log.tf,fromEstimationScale=sir.exp.tf)
```

After these codes, will the `pmcmc` step confirm that all the parameters are positive? Or there is some problem of using it?

Another point that I don't quite understand is also this log transform. So during the `pmcmc`, the pomp use the log transform to propose the parameter, and then use the exp transform to let the parameter goes to the original scale, and then use the parameter in the original scale to sampling the dataset? Did I understand it correctly?

**Comment by njuxcui** [comment]
One more thing, the prior I am now using for the pmcmc is:

```
sir.dprior<-function(params,...,log){
  f<-(dunif(params[1],min=hyperparams$min[1],
            max=hyperparams$max[1],log=TRUE)+
        dgamma(params[2],shape=0.001,rate=1,log=TRUE)+
        dunif(params[3],min=hyperparams$min[3],
              max=hyperparams$max[3],log=TRUE)+
        dgamma(params[4],shape=1,rate=2,log=TRUE)+
        log(ddirichlet(params[5:7]/(sum(params[5:7])),c(900,3,9))))
  if(log) f else exp(f)
}

pmcmc<-foreach(i=1:3,.combine=c) %dopar%{
  pmcmc(pomp(sir,dprior=sir.dprior),start=theta.mif,Nmcmc=20000,Np=1,max.fail=Inf,
        proposal=mvn.diag.rw(c(be=0.01,mu=0.01,rho=0.01,S.0=0.01,I.0=0.01,R.0=0.01)))
}
```

Former, when I am not using this prior, the pomp `pmcmc` works well. But after I using this prior, problems come out. Any problem here?

**Comment by njuxcui** [comment]
I have tried it several times, but it doesn't work out. So for my SIR model using the lmcmc, how could I make log transformation to the parameter and exp transformation to transform the parameter back to keep the parameter positive?

**Comment by njuxcui** [comment]
I have tried it several times, but it doesn't work out. So for my SIR model using the `pmcmc`, how could I make log transformation to the parameter and exp transformation to transform the parameter back to keep the parameter positive?

**Comment by kingaa** [comment]
You are assuming that `pmcmc` makes use of the parameter transformations you provided.  This is not correct.  `pmcmc` does not transform the parameters at all.  One might think that it would be easy to provide such a facility.  However, to properly transform the parameters, one would have to transform the prior as well, or the proposal probability distribution, at least one of which will be non-trivial, in general.  Therefore **pomp** avoids it.

A strategy to enforce positivity on parameters for PMCMC is to use a prior that puts zero weight on negative values of the parameter.  I can't verify that the prior you specify above has this property or not.  Can you check?

**Comment by njuxcui** [comment]
That is the problem. I though it has done the log transform. The problem comes from that the parameter jump to the negative value and causes the error. Thank you for your help.
