### ISSUE TITLE
 double exp(double) in rprocess returns nan

### ISSUE THREAD

**Issue by Spatial-R** [kingaa/pomp#26]
My problem is that i want to test the covariate effect on the FOI and reporting rate, therefore i use a **exp** function in the rprocess to make sure the FOI is non-negative and monotonic increasing. However, it returns nan during the simulation. I try to use the **pow** function to replace the **exp** function, but it still doesn't work. My session infomation: 

>  R version 3.3.1 (2016-06-21)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.5 LTS  
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods  base
> other attached packages:
> [1] doMC_1.3.4      iterators_1.0.8 foreach_1.4.3   magrittr_1.5   pomp_1.9
> loaded via a namespace (and not attached):
>  [1] deSolve_1.13     subplex_1.1-6    rsconnect_0.4.3  tools_3.3.1   coda_0.18-1      mvtnorm_1.0-5    codetools_0.2-14 grid_3.3.1    digest_0.6.10    nloptr_1.0.4     lattice_0.20-34

 [Codes](https://github.com/Spatial-R/Dynamic-Model-for-Infectious-Disease/blob/master/examples/temp1temp3global.R) and [Data](https://github.com/Spatial-R/Dynamic-Model-for-Infectious-Disease/blob/master/examples/dataset.RData)

**Comment by kingaa** [comment]
The `exp` function is part of the [standard C math library](https://en.wikipedia.org/wiki/C_mathematical_functions).  You can look there to see why you are getting `NaN`.  Presumably, it is because you are calling `exp(x)` with `x=NaN`.

**Comment by Spatial-R** [comment]
Yes. I tested the value and found the error is because the x=nan. But i found a strange thing:
for example, `x=MT*bmt`, MT is the covariate with the range between -2 and 2. Why the parameter bmt will be valued as nan when using the **mif2** function?

**Comment by kingaa** [comment]
You are estimating `bmt`, no?  `mif2` explores the range of `bmt`.  Have you done anything to make sure it remains valid?

**Comment by Spatial-R** [comment]
Yes. i want to estimate the parameter **bmt**.  I utilise a global search and start the parameter randomly drawing from the box: 

> theta.lo <-c(mu=5.93/1000,sigma=5,gamma=5,alpha=3.115105e01,iota=5.952648e+00,rho=0.2,
> R0=20, sigmaSE=0,psi=0.1,cohort=0,amplitude=0, S_0=0.02,I_0=2e-06, E_0=2e-06,
> bmt=-2,gmt=-2)  
> theta.hi <- c(mu=5.93/1000,sigma=40,gamma=40,alpha=1,iota=40,rho=0.7,R0=200,
>              sigmaSE=1,psi=0.4,cohort=1,amplitude=1,S_0=0.03,I_0=0.0001,E_0=0.0001,bmt=2,gmt=2)`

After running the mif function, there will be an error: *\* "in ‘pfilter’: ‘dmeasure’ returns non-finite value*\* , but not every time. If i change the box for the **bmt** value with 0-1, there will be no error, only with some warnings (1 filtering failure occurred) .

Therefore, i guess the start value for parameter **bmt** will influence the model performance. But this phenomenon makes no sense because the FOI still positive in spite of the negative value of parameter **bmt**, due to the **exp** function in the model(**exp(MT*bmt)**)

**Comment by kingaa** [comment]
I thought you had established that the problem is not that `bmt` becomes negative but that it becomes non-finite.

Have you tried to use debugging tools to figure out why and where the parameter becomes non-finite?

Do you understand how `mif2` estimates parameters?  If not, I suggest you read some of the literature on the subject.  There are references in the documentation and tutorials on the website.  You should know that there is more in play than just the starting value of each parameter.

In general, the functioning of the open source software community depends on users like you doing their homework before asking for help from developers.
