### ISSUE TITLE
Issue with abc.R test file.

### ISSUE THREAD

**Issue by exproject** [kingaa/pomp#28]
Hi,

I'm running into issues with the abc test file.

Lines 101 and 102 produce this error:

```
> try(abc7 <- c(abc2,abc3))
Error in validObject(.Object) : 
  invalid class “abcList” object: error in ‘c’: to be combined, ‘abc’ objects must have chains of equal length
> try(abc7 <- c(abc7,abc3))
Error in validObject(.Object) : 
  invalid class “abcList” object: error in ‘c’: to be combined, ‘abc’ objects must have chains of equal length
```

But that appears to be because of line 58: abc3 <- continue(abc3,Nabc=700)

Once 58 is omitted the chains error goes away, but more warning messages start to follow from there

Lines 106-108:

```
> plot(abc2,scatter=TRUE,y=NA)
Warning message:
in ‘plot-abc’: ‘y’ is ignored 
> plot(abc7,scatter=TRUE,y=NA)
Warning message:
in ‘plot-abc’: ‘y’ is ignored 
> try(plot(abc7,pars=c("alpha.1"),scatter=TRUE,y=NA))
Error : in ‘plot-abc’: can't make a scatterplot with only one variable
In addition: Warning message:
in ‘plot-abc’: ‘y’ is ignored 
```

Line 145:

```
 abc9 <- abc(
+     abc8,Nabc=1,probes=probes.good,scale=scale.dat,epsilon=5,
+     proposal=mvn.rw.adaptive(rw.var=vmat,scale.start=500,shape.start=100))
Warning messages:
1: In chol.default(covmat, pivot = TRUE) :
  the matrix is either rank-deficient or indefinite
2: in ‘mvn.rw.adaptive’: degenerate proposal 
```
Lines 149, 151, 155 and 161 with their own but similar errors :)

```
> try(abc(abc2,Nabc=3,probes=probes.good,scale=scale.dat,epsilon=1,
+         proposal=function(theta,...)stop("urp!")))
Error : in ‘abc’: in proposal function: urp!
> try(abc(pomp(ou2,dprior=function(params,log,...)stop("oof!")),
+         Nabc=3,probes=probes.good,scale=scale.dat,epsilon=1,
+         proposal=mvn.diag.rw(c(alpha.1=0.01,alpha.2=0.01))))
Error : in ‘abc’: ‘dprior’ error: oof!
```
```
> try(abc(abc2,Nabc=3,probes=probes.good,scale=scale.dat,epsilon=1,
+         proposal=function(theta,...) {
+             neval <<- neval+1
+             if (neval>1) stop("bif!") else theta
+         }))
Error : in ‘abc’: in proposal function: bif!
```
```
> try(abc(
+     pomp(ou2,dprior=function(params,log,...) {
+         neval <<- neval+1
+         if (neval>10) stop("eep!")
+         else if (log) 0
+         else 1
+     }),Nabc=20,probes=probes.good,scale=scale.dat,epsilon=1,
+     proposal=mvn.diag.rw(c(alpha.1=0.01,alpha.2=0.01))))
Error : in ‘abc’: ‘dprior’ error: eep!
```
And so on. All of the try statements have similar ends. Would love to play with this a bit more, just hoping to use this file as a reference.

**Comment by kingaa** [comment]
Thanks for the detailed explanation.  The purpose of the test files is to test the code.  Those errors you report are intentional: they're meant to trigger the error-handling portions of the code.  The test codes are really the farthest thing from tutorials and are probably the worst way to go about learning how to use `pomp`!  In fact, they're designed to do trivial things in lots of ways, most of them suboptimal, strange, or downright silly.  To learn about the package, I'd recommend starting with the tutorials in the documentation.

**Comment by exproject** [comment]
Thanks for the info on that being an error handling test more than an example. I've looked around and I don't know if I'm missing anything, but are there any examples of an ABC model in the FAQs / vignettes?

**Comment by kingaa** [comment]
Try the [JSS paper](http://kingaa.github.io/pomp/vignettes/pompjss.pdf).

**Comment by christelpei** [comment]
Thanks for the link to the paper that was also very helpful for me to get started with ABC!
Still, I would be very happy if more examples should show up on this issue as I was learning myself by trial and (many) errors. It took me for example a while to notice that the epsilon parameter is very model dependent and if too small nothing will happen (well, obvious after I understood). Currently I am trying to find out how best to do inference on a subset of the model parameters while keeping others fixed. It seems that parameters that do not show up in proposal = mvn.diag.rw(...) (or equivalently (?) with standard deviation set to 0) are not considered in the inference (though apparently still a prior needs to be defined for these parameters). If I however choose very narrow priors with small standard deviations in the above function for these parameters, no parameters will change in the inference procedure and I get many warnings:

> In rnorm(n = n, mean = theta[parnm], sd = rw.sd) : NAs produziert

I assume that acceptance rates become very small here but do not quite understand yet...
Alternatively, I have provided constant parameters as covariates using the variable covar in the pomp object and have done inference on the other parameters which also seems to work fine. Will this be equivalent to the solutions above?

**Comment by kingaa** [comment]
Hi Christel,

Apologies for taking so long to get back to you.
Yes, if you leave parameters out of the proposal, they will stay at their predetermined value.
With respect to the question of priors, **pomp** is very flexible.  In particular, you can put a prior on a parameter, or not (which is mathematically equivalent to putting a degenerate, i.e., Dirac delta, prior on that parameter).  You can even use some of the parameters in the `params` slot as hyperparameters, i.e., you can allow the prior to depend on parameters.  [*Actually*, the right way to think about it that there is no plural form of "prior": there is a single joint prior distribution on the parameters, which can be degenerate in some directions and flat in others.]
Yes, if the priors are narrow, then you have assumed there is very little uncertainty in those parameters, therefore little interest in investigating alternatives, therefore little change.
I am not sure why you are seeing the "NAs produced" warnings.  Difficult to say without knowing more.  Have you tried to use `debug` to see what the parameters being passed to `rnorm` are when the warnings are produced?
You can pass parameter as covariates, which will work, but is suboptimal in the sense that covariates are assumed to be time-dependent, which will lead to a certain amount of unnecessary work in interpolating them.  Alternatively, you can pass constant parameters using the `globals` facility (if you are using Csnippets) or via the `userdata` facilities.  Or you can hard-code them.  Or, as I say, you can pass them via the `params` argument and simply treat them as fixed.

**Comment by christelpei** [comment]
Thanks for the detailed feedback that helps me to find the best way "to treat a parameter as fixed" - or more generally to define more complex joint priors. Could I realize the Dirac delta prior on a parameter by setting the SD in the proposal vector to zero (seems to work) or equivalently to set identical lower and upper bounds in the example from the Journal of Statistical Software paper (section 4.4. and 4.7 on PMCMC and ABC) adding "na.rm =TRUE" in the sum function within the prior definition (seems also to work, though less elegant...)?
I have come to these conclusions, as I have found no way for how to provide a reduced set of parameters in the prior as compared with the parameters in the pomp object. I also wonder - assuming that the prior takes parameters form the pomp object by default -  where is the parameter "log" of the prior function derived from in the above example from  the Journal of Statistical Software paper (and should the prior be log-transformed or not?)

**Comment by kingaa** [comment]
Try posting some code (for a simple problem).  I can show you what I mean.  Open another issue when you do so, so that the issue title is related to the question.  The issue you raise is unrelated to the original post.
