### ISSUE TITLE
How to demonstrate the result properly?

### ISSUE THREAD

**Issue by LUOSDU** [kingaa/pomp#32]
Thanks for a great package which helps me a lot on the research!
After running a few `mif2` code, I think I have find the highest loglik. 

1.  Can I determine that the set of parameters value with highest log likelihood is the best result? 
2. Why don't paper such as _He , 2010_ emphasize the confidence interval for parameters? 
3. How to demonstrate the result properly? Which figures should I put into the paper?

Thank you!

**Comment by kingaa** [comment]
These are very general questions.  Let me give you some very general responses.

1. The sense in which maximum likelihood (ML) parameters can be regarded as "best" is described by the ML theory.  There are many expositions of this theory.  See, e.g., Pawitan, Y., In All Likelihood: Statistical Modelling and Inference Using Likelihood,Oxford University Press, 2001.

2. Our preferred method for estimating confidence intervals (CI) is profile likelihood.  In He et al. (2010), we did compute CI for some parameters of interest, but did not do it for all parameters.

3. Your third question depends very much on what your result is.  There will never be a way to answer such a question in generality.  Similarly, which figures you put in the paper depends very much on what you want to say, doesn't it?
