### ISSUE TITLE
Issues with parallel computing

### ISSUE THREAD

**Issue by christelpei** [kingaa/pomp#37]
Although I understand that this is probably not really within the realm of your package I wonder whether you had similar problems - and maybe even have found a solution?! In your JSS paper (and supplementary code provided) you give examples how to parallelize computations. I have adapted this along the lines
```
library(doMC)
library(foreach)
registerDoMC()

pmcmc1 <- foreach(
    i=1:5,
    .inorder=FALSE,
    .packages="pomp",
    .combine=c,
    .options.multicore=list(set.seed=TRUE)
  ) %dopar% {
    pmcmc(pomp(sir, dprior = sir.dprior), start = para,
          Nmcmc = 600000, Np = 100, max.fail = Inf,
          proposal = mvn.diag.rw(c(Beta=0.02, gamma=0.01,mu =0.05, sigma = 0.0, 
          cov_primary=0.1, cov_child =0.1, cov_teen =0.1, rho1=0.005, rho2 = 0.005, 
          rho3=0.001,rho4=0.001,rho5=0.001, dispersion = 0)))
  }
```
for which I get an error message as described here: 
https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17137

If I switch off prescheduling, i.e. 

` .options.multicore=list(set.seed=TRUE, preschedule = FALSE)`

there is still the message about problems in fork.c - only the final message changes from

> In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  all scheduled cores encountered errors in user code

to 

> In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  5 function calls resulted in an error

I do not find the information provided following the link above too helpful, particularly regarding the fact that the traces are about the size of 50MB (and not in the order of GB where problems were expected according to Brian Ripley). Have you encountered similar problems or could help me with any clues?

**Comment by kingaa** [comment]
I don't see the error message you are getting from the first code. 
Some things to try:

1. Wrap each call to `pmcmc` inside a `try` statement, and remove the `.combine` argument, so that you can see if the individual parallel runs are giving errors, or if the errors are arising from the parallelization itself.
1. Try returning less information from each run.  The `pmcmc` object returned by each individual parallel job is potentially quite large.  Try it with fewer `Nmcmc` iterations.  Or, what if you extract, e.g., only the last few iterations?
1. Try a different parallel backend.  For example **doMPI** or **doParallel** with a socket cluster.

**Comment by christelpei** [comment]
Thanks for the helpful suggestions! The individual runs appear to run fine (point 1), fewer Nmcmc iterations would not really be an opition in my case, maybe thinning the traces before combing the parallel runs (point 2), though I have not tried it. Point 3 finally did the job, i.e. the following code worked as it should:

```
  library(doParallel)  
  library(foreach)
  registerDoParallel() 

  pmcmc1 <- foreach(
    i=1:5,
    .inorder=FALSE,
    .packages="pomp",
    .combine=c,
    .options.multicore=list(set.seed=TRUE, preschedule = FALSE)
  ) %dopar%
  {
    pmcmc(pomp(sir, dprior = sir.dprior), start = para,
          Nmcmc = 600000, Np = 100, max.fail = Inf,
          proposal = mvn.diag.rw(c(Beta=0.02, gamma=0.01,mu =0.05, sigma = 0.0, 
          cov_primary=0.1, cov_child =0.1, cov_teen =0.1, rho1=0.005, rho2 = 0.005,     
          rho3=0.001,rho4=0.001,rho5=0.001, dispersion = 0)))
  }
```

Though I have not been digging into the causes why doParallel works and doMC does not...

**Comment by kingaa** [comment]
Well, that's interesting.  I hadn't seen such a clear-cut example of success under one parallel backend and failure under another.  It would be instructive, and probably helpful, to bring this up with the **doMC** developers!

As an aside, regarding point 2 above, one could reduce the size of the object returned by each parallel job without reducing MCMC iterations by, for example, extracting the traces (`conv.rec`) and doing the thinning on each parallel job's output *before* returning and combining.  I wonder if this smaller output would be palatable to **doMC**.  It might be interesting to know, though of course, you would like not to have to tailor your algorithm to the needs of the parallel codes.

I'm going to close this issue now, but feel free to reopen if there is more to discuss.
