### ISSUE TITLE
Fitting a mixed model on replicate time series

### ISSUE THREAD

**Issue by noamross** [kingaa/pomp#40]
I am looking for any documentation or examples of how one might use **pomp** to fit a mixed model over multiple time series.  I have time series data for a livestock disease outbreaks on multiple farms, and would like to fit the same model simultaneously across all of them, estimating key epidemiological parameters (contact rate, etc.) as draws from a common distribution. This can be done with Stan if I used ODE trajectory matching, but extinction processes are important in this case so I have been opting to use a Gillespie simulation in *pomp*.  Any information you can direct me to?

**Comment by kingaa** [comment]
Interesting problem.  The [**panelPomp** package](http://cbreto.github.io/panelPomp/), under development by Carles Breto, builds on **pomp** to tackle this kind of problem.  Specifically, it is possible to formulate a mixed model such as you describe.  I encourage you to contact @cbreto for more information.

**Comment by cbreto** [comment]
Thanks Aaron! I’ll push the contacts example to the panelPomp github repo. This should help illustrate the capability of panelPomp to specify mixed models much better than the current panelGompertz example. Best for the first SBEID session and getting all those users installing pomp in such a diverse array of machine!

Best,
carles
