### ISSUE TITLE
How Could we add A seasonal state?

### ISSUE THREAD

**Issue by ayoubsbitti** [kingaa/pomp#41]
In state space model we could probably be interested in adding a seasonal state, for example :
```
       t = 1......T ;   
       y(t) = mu(t) + Seas(t) + eps(t) ; 
       mu(t+1) = mu(t) + u(t)
       Seas(t) = = - sum(Seas(t-j) , j = 1 .... S-1 ) + w(t)
```
with S the number of seasons.
Where eps(t) , u(t) , w(t) are errors following a normal distribution with mean 0 and a given variance. 

Please How can I specify rprocess   and rmeasure for  this case?
Thanks in advance. 
note that the seasonal components could be modeled with  by vectors of size S : number of seasons , and each components follow a random walk  constrained to sum to zero for each time t 

for more about modeling seasonality please have a look at this paper : link below 
http://ec.europa.eu/eurostat/documents/3888793/5842169/KS-DT-06-019-EN.PDF/f046f027-ef69-4095-aa49-d55119998d19
Thanks in advance

**Comment by kingaa** [comment]
There's an example of a seasonal model in the [JSS paper](https://kingaa.github.io/pomp/vignettes/pompjss.pdf), many others in applications papers we've published (e.g., [Martinez-Bakker et al 2015](http://doi.org/10.1371/journal.pbio.1002172), [Lavine et al 2013](http://doi.org/10.1371/journal.pone.0072086), [He et al 2010](http://doi.org/10.1098/rsif.2009.0151)), and some codes that can be cribbed from [here](http://kingaa.github.io/pomp/vignettes/He2010.html) and [here](http://kingaa.github.io/sbied/polio/polio.html).

I'm closing this issue now, but feel free to reopen if more information is needed, or if you have other questions on this specific topic.
