### ISSUE TITLE
Missing packages in "Getting started" vignette

### ISSUE THREAD

**Issue by tomessilva** [kingaa/pomp#45]
This vignette depends on several packages besides "pomp": from what I could determine, at least "ggplot2", "magrittr", "foreach", "iterators" and "coda" (but perhaps more?). From these packages, only "coda" is being specifically loaded in the vignette.

Perhaps these packages should be explicitly loaded in the vignette (via library() or require()), to make it easier for people to follow the vignette?

**Comment by kingaa** [comment]
Done.
