### ISSUE TITLE
FAQ: Issue 4.1

### ISSUE THREAD

**Issue by tomessilva** [kingaa/pomp#47]
The FAQ has been very helpful in interpreting and locating problems in my Csnippets.

One suggestion to improve Issue 4.1 of the FAQ is to add another common cause for problems in the `dmeasure` function: trying to modify the pre-declared `lik` variable without first initializing it to zero. I know it's a trivial C rookie error, but perhaps adding that line to the FAQ may help in the future at least one or two people like me, saving them a couple of hours ;)

On the other hand, the suggestion of using `Rprintf` to diagnose problems was a good hint in the right direction.

Thanks, once again.

**Comment by kingaa** [comment]
Done.
