### ISSUE TITLE
time varying random walk standard deviations

### ISSUE THREAD

**Issue by martinezmicaela** [kingaa/pomp#5]
The developer version of pomp 0.44-1 has time varying random walk standard deviations. It would be great if this feature were integrated into the next release version. 

-Micaela

**Comment by kingaa** [comment]
pomp is now at version 1.2.1.5, some 540 commits and 32 months newer than version 0.44-1.  The functionality requested has been present via the 'mif2' function since version 0.69-5 (July 2015).  See '?mif2' and the tutorials for information.
