### ISSUE TITLE
Fitting ecological data with multiple replicates per time point

### ISSUE THREAD

**Issue by murallcl** [kingaa/pomp#51]
Thank you very much for this great package. I am interested in using it to fit ecological data that has various replicate measures per time point. Before trying the particle filtering I am running some examples using MLE. Instead of sending my exact example I think it would be easier to simply use an example you have in "Model-based Inference in Ecology and Epidemiology (a short course)". Please see lesson "Introduction to inference: parameter estimation",  in the first example under the section "Likelihood", you introduce a the dataset of community A into the pomp function. Say now that you have three replicates per time point, that would give you a dataset like the example one I upload here. 
If I give `pomp(data= "niameyAreps", ...)` then I get an error that says  
```
 in 'pomp': 'times' must be an increasing numeric vector
``` 
So my question is, can pomp take data that has multiple replicates per time point? and if so, then how do I restructure the data or the code so that it can use this extra information. 

[niameyAreps.zip](https://github.com/kingaa/pomp/files/1295656/niameyAreps.zip)

**Comment by kingaa** [comment]
Since you don't include the full codes, it's not possible to know for sure, but you appear to have not specified the `times` properly.  In the data file you include, there are three observations per time point, on three separate lines.  Rearrange the data so that you have one line per time point, with four columns (time, obs 1, obs 2, obs 3).

Also, please read FAQ 1.1 and FAQ 3.2.  In particular, perhaps you can help me to improve FAQ 3.2.

**Comment by murallcl** [comment]
Hi. Yes, rearranging the data into the format you suggested worked. I am now working on a multivariate version. When I have a working example I will post. Thank you.

**Comment by kingaa** [comment]
I am closing this issue now.  Please do re-open it when you have a working example!

**Comment by murallcl** [comment]
[example_fitting_LVcomptn.zip](https://github.com/kingaa/pomp/files/1425098/example_fitting_LVcomptn.zip)
Hi again,
Here is an example using the 2-species Lotka-Volterra competition model and some made-up data with multiple replicates per timepoint. In addition to having to transform the data as you suggested (in the csv file), I found you had to transform the data again (after running through pomp) in the log-likelihood function (line76). I found fitting both variables pretty straightforward, except this is only a MLE example, so it might be more complicated when using the pomp models/particle filtering. 
The fits I get aren't great but that wasn't the point of the exercise.
Let me know if you think I'm doing something wrong or missing something.
I attach the data files and the code.
Best, Carmen Lia

![fit_wdata](https://user-images.githubusercontent.com/31885778/32144137-732d669e-bcb4-11e7-8c4c-66283510bbb8.png)
![fit2](https://user-images.githubusercontent.com/31885778/32144138-7350118a-bcb4-11e7-8e18-4340ce34ea9b.png)

```
# --------------------------------------------------------------------------------------
#
#       Example Lotka-Volterra competition model data with multiple replicates per timepoint
#MLE, negbinom, fitting 2 variables
#by Carmnen Lia Murall

#libraries:
library(stats4)
library(bbmle)
library(deSolve)
library(ggplot2)

#pomp prelims:
library(pomp)
stopifnot(packageVersion("pomp")>"1.4.9")
library(plyr)
library(reshape2)
options(stringsAsFactors=FALSE)
theme_set(theme_bw())
set.seed(1173439184)

#-----------------------------  data  --------------------------------------------------
#dataset
file<-read.csv("simulated_LVcompdata_singlecolumn.csv")

#plot data
ggplot()+
  geom_point(file,mapping = aes(x=Time,y=counts,color=Species),size=1.5)+
  theme_classic()+
  labs(y="counts", x="days")

#get summary of the data
library(lattice)
library(Rmisc)
sumry <-summarySE(data=file, measurevar="counts",groupvars=c("Time","Species"))
sumry 
#reorganize, new dataframe
sumryN1 <-subset(sumry, Species== "N1")
sumryN2 <-subset(sumry, Species== "N2")
dataset2V<-data.frame("Days"=sumryN1$Time, "avgN1"=sumryN1$counts, "avgN2"=sumryN2$counts)

#plot means with sd
ggplot(dataset2V,aes(x=Days))+
  geom_point(aes(y=avgN1),color='red')+
  geom_point(aes(y=avgN2),color='turquoise')+
  geom_line(aes(y=avgN1),color='red')+
  geom_line(aes(y=avgN2),color='turquoise')+
  geom_linerange(aes(ymin=avgN1-sumryN1$sd, ymax=avgN1+sumryN1$sd),color='red') +
  geom_linerange(aes(ymin=avgN2-sumryN2$sd, ymax=avgN2+sumryN2$sd),color='turquoise') +
  labs(y="mean (counts)", x="days")


#------------------------- now use a file with Reps as 'obs'in columns-----------------------

file_reps<-read.csv("simulated_LVcompdata.csv")

#make a pomp object
pomp(
  data=file_reps, 
  times="Time",
  t0=0,  
  skeleton=vectorfield( 
    Csnippet("
             DN1 = r1*N1*(K1-N1-a12*N2)/K1;
             DN2 = r2*N2*(K2-N2-a21*N1)/K2;")),
  initializer=Csnippet("       
                       N1 = N1_0;
                       N2 = N2_0;"),
  statenames=c("N1","N2"),  
  paramnames=c("r1","r2","a12","a21","K1","K2","N1_0","N2_0")) -> dataReps  

#make log-likelihood function
loglik.negbin <- function (params) {
  x <- trajectory(dataReps,params=params) 
  sum(dnbinom(x=t(obs(dataReps)[1:3,1:11]), #must be transformed into format pomp can read 
              mu=params["p"]*x["N1",,],size=1/params["theta"],log = TRUE)+
        dnbinom(x= t(obs(dataReps)[4:6,1:11]),
                mu=params["p"]*x["N2",,],size=1/params["theta"],log = TRUE)) 
}

logit <- function (g) log(g/(1-g))   
expit <- function (f) 1/(1+exp(-f))  

f4 <- function (par) {
  params <- c(r1=expit(par[1]),r2=expit(par[2]), a12=expit(par[3]),a21=expit(par[4]),theta=exp(par[5]),p=expit(par[6]),
              K1 = 180, K2 = 100,
              N1_0=10,  N2_0=10) 
  -loglik.negbin(params)
  }

guess <- c(logit(0.3),logit(0.4),logit(0.3),logit(0.4),log(0.9),logit(0.8))
fit4 <- optim(f4, par=guess)
fit4

mle6 <- c(r1=expit(fit4$par[1]),r2=expit(fit4$par[2]),a12=expit(fit4$par[3]),a21=expit(fit4$par[4]),theta=exp(fit4$par[5]),p=expit(fit4$par[6]))
signif(mle6,6)

#compute the model's trajectory
coef(dataReps) <- c(mle6, 
                    K1 = 180, K2 = 100,
                    N1_0=10, N2_0=10) #new vector with estimated parameters
x <- trajectory(dataReps,as.data.frame=TRUE) #run model

#plot model prediction with data
ggplot(data=join(as.data.frame(dataReps),x,by='time'), 
       mapping=aes(x=time))+
  geom_line(aes(y=N1),color='red')+ 
  geom_line(aes(y=N2),color='turquoise')+
  geom_point(aes(x=file_reps$Time,y=file_reps$N1_obs1),color='red',size=1.5)+
  geom_point(aes(x=file_reps$Time,y=file_reps$N1_obs2),color='red',size=1.5)+
  geom_point(aes(x=file_reps$Time,y=file_reps$N1_obs3),color='red',size=1.5)+
  geom_point(aes(x=file_reps$Time,y=file_reps$N2_obs1),color='turquoise',size=1.5)+
  geom_point(aes(x=file_reps$Time,y=file_reps$N2_obs2),color='turquoise',size=1.5)+
  geom_point(aes(x=file_reps$Time,y=file_reps$N2_obs3),color='turquoise',size=1.5)+
  theme_classic()+
  labs(y="counts",x="time,days")

coef(dataReps) #print params


#for ribbons
model.predN1 <- trajectory(dataReps)["N1",,]
model.predN2 <- trajectory(dataReps)["N2",,]

library(plyr)
raply(2000,rnbinom(n=length(model.predN1),
                    mu=coef(dataReps,"p")*model.predN1,
                    size=1/coef(dataReps,"theta")))-> simdatN1
aaply(simdatN1,2,quantile,probs=c(0.025,0.5,0.975))->quantilesN1

raply(2000,rnbinom(n=length(model.predN2),
                    mu=coef(dataReps,"p")*model.predN2,
                    size=1/coef(dataReps,"theta")))-> simdatN2
aaply(simdatN2,2,quantile,probs=c(0.025,0.5,0.975))->quantilesN2

typN1<-sample(nrow(simdatN1),1)
typN2<-sample(nrow(simdatN2),1)

gN1<- cbind(as.data.frame(dataReps)[1:11,1:4],quantilesN1,typical=simdatN1[typN1,])
gN2<- cbind(as.data.frame(dataReps)[1:11,c(1,5:7)],quantilesN2,typical=simdatN2[typN2,])

#plot model prediction with means and ribbons
ggplot(data=join(as.data.frame(dataReps),x,by='time'), 
       mapping=aes(x=time))+
  geom_line(aes(y=N1),color='red')+ 
  geom_line(aes(y=N2),color='turquoise')+
  geom_point(data=dataset2V,aes(x=Days,y=avgN1),color='red',size=1.5)+
  geom_point(data=dataset2V,aes(x=Days,y=avgN2),color='turquoise',size=1.5)+
  geom_linerange(aes(ymin=dataset2V$avgN1-sumryN1$sd, ymax=dataset2V$avgN1+sumryN1$sd),color='red') +
  geom_linerange(aes(ymin=dataset2V$avgN2-sumryN2$sd, ymax=dataset2V$avgN2+sumryN2$sd),color='turquoise') +
  geom_ribbon(data=gN1,aes(x=time,ymin=gN1$`2.5%`,ymax=gN1$`97.5%`),fill="red",alpha=0.2)+
  geom_ribbon(data=gN2,aes(x=time,ymin=gN2$`2.5%`,ymax=gN2$`97.5%`),fill="turquoise",alpha=0.2)+
  theme_classic()+
  labs(y="counts",x="time, days")

coef(dataReps) #print params again
```

**Comment by kingaa** [comment]
@liachica, thanks for a great example!  In it, you say that you are using maximum likelihood to estimate parameters.  This is a bit imprecise.  ML in the context of a deterministic process model and a stochastic measurement model is more precisely referred to as "trajectory matching".  I've edited your example in the following to show off better ways of accomplishing the same objective.  In particular, one can use **pomp**'s `traj.match` function to accomplish trajectory matching, saving you the need to code up a call to `optim` yourself.  The codes below also show how to use `rmeasure` to simulate from the measurement model.

I propose that you edit the following as you see fit (the data file and .Rmd file are in the zip file referenced at the bottom).  We can work toward making this a nice [vignette on the **pomp** homepage](http://kingaa.github.io/pomp/docs.html).

Lotka-Volterra competition with replicated observations
================
Carmen Lia Murall and Aaron A. King

------------------------------------------------------------------------

In this simple example, we show how one can fit a POMP to data consisting of multiple independent observations per time point.

The model in our example is deterministic, so we use trajectory matching to estimate the parameters by maximum likelihood.

First, we load some needed packages.

``` r
library(pomp)
stopifnot(packageVersion("pomp")>="1.5")
library(plyr)
library(magrittr)
library(readr)
library(reshape2)
library(ggplot2)
options(stringsAsFactors=FALSE)
theme_set(theme_bw())
set.seed(1173439184)
```

Next, we load and plot the data. Note that there are three observations per time point, for each of two species.

``` r
read_csv("LV_data.csv") %>%
  rename(c(Time="time",Species="species")) -> dat

dat %>%
  ggplot(aes(x=time,y=counts,color=species))+
  geom_point(size=1.5)+
  labs(y="counts")
```

![load_data-1](https://user-images.githubusercontent.com/1863307/32173733-49195794-bd56-11e7-9633-27b2e4953c2b.png)

``` r
dat %>%
  ddply(~time+species,summarize,m=mean(counts),sd=sd(counts)) %>%
  ggplot(aes(x=time,y=m,ymin=m-sd,ymax=m+sd,group=species,color=species))+
  geom_line()+geom_linerange()+
  labs(y="counts")
```

![load_data-2](https://user-images.githubusercontent.com/1863307/32173725-43763a6e-bd56-11e7-9d0f-0ef9900c9b84.png)

Now we reshape the data, so that we have one row for each timepoint, and one column for each observation.

``` r
dat %>%
  ddply(~species+time,mutate,rep=seq_along(time)) %>%
  dcast(time~species+rep,value.var="counts") %>%
  arrange(time) -> dat2
dat2
```

    ##    time N1_1 N1_2 N1_3 N2_1 N2_2 N2_3
    ## 1     1    0   11    1    0   14    3
    ## 2    20    4   16   19    1   44   48
    ## 3    40   24    8   33   89   78   92
    ## 4    60   14   31   36  107  116  127
    ## 5    80   35   45   50  101   75   98
    ## 6   100   75   73   54   72   62   81
    ## 7   120   92   64   93   65   43   50
    ## 8   140  112  103  104   45   56   63
    ## 9   160  113  145   88   56   77   61
    ## 10  180  122  117   90   62   67   47
    ## 11  200  120  128  102   66   71   63

We construct a pomp object in the usual way. Here, the process model is a deterministic vectorfield.

The measurement model assumes that the observations arise from a negative binomial process. Note that we use the `dnbinom_mu` function from the [**R** C API](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Distribution-functions).

``` r
dat2 %>%
  pomp(
    times="time",
    t0=0,
    skeleton=vectorfield(
      Csnippet("
            DN1 = r1*N1*(K1-N1-a12*N2)/K1;
            DN2 = r2*N2*(K2-N2-a21*N1)/K2;")),
    initializer=Csnippet("
            N1 = N1_0;
            N2 = N2_0;"),
    dmeasure=Csnippet("
            lik = dnbinom_mu(N1_1,1/theta,p*N1,1)+
                    dnbinom_mu(N1_2,1/theta,p*N1,1)+
                    dnbinom_mu(N1_3,1/theta,p*N1,1)+
                    dnbinom_mu(N2_1,1/theta,p*N2,1)+
                    dnbinom_mu(N2_2,1/theta,p*N2,1)+
                    dnbinom_mu(N2_3,1/theta,p*N2,1);
            lik = (give_log) ? lik : exp(lik);"),
    rmeasure=Csnippet("
            N1_1 = rnbinom_mu(1/theta,p*N1);
            N1_2 = rnbinom_mu(1/theta,p*N1);
            N1_3 = rnbinom_mu(1/theta,p*N1);
            N2_1 = rnbinom_mu(1/theta,p*N2);
            N2_2 = rnbinom_mu(1/theta,p*N2);
            N2_3 = rnbinom_mu(1/theta,p*N2);"),
    toEstimationScale=Csnippet("
            Tp = logit(p);
            Ttheta = log(theta);
            Tr1 = logit(r1);
            Tr2 = logit(r2);
            Ta12 = logit(a12);
            Ta21 = logit(a21);"),
    fromEstimationScale=Csnippet("
            Tp = expit(p);
            Ttheta = exp(theta);
            Tr1 = expit(r1);
            Tr2 = expit(r2);
            Ta12 = expit(a12);
            Ta21 = expit(a21);"),
    statenames=c("N1","N2"),
    paramnames=c("p","theta","r1","r2","a12","a21","K1","K2","N1_0","N2_0")
  ) -> po
```

Now we use trajectory matching to estimate the parameters. We hold several of the parameters fixed and estimate the others. Trajectory matching is accomplished with a call to `traj.match`. We apply this twice, to ensure convergence.

``` r
po %>% traj.match(start=c(K1=180,K2=100,N1_0=10,N2_0=10,r1=0.3,r2=0.4,
                          a12=0.3,a21=0.4,theta=0.9,p=0.8),
                  est=c("r1","r2","a12","a21","theta","p"),
                  method="Nelder-Mead",transform=TRUE,maxit=1000) -> fit
summary(fit)
```

    ## $params
    ##           K1           K2         N1_0         N2_0           r1 
    ## 180.00000000 100.00000000  10.00000000  10.00000000   0.03099317 
    ##           r2          a12          a21        theta            p 
    ##   0.10134078   0.51185185   0.30807572   0.11472813   0.91071327 
    ## 
    ## $loglik
    ## [1] -293.763
    ## 
    ## $eval
    ## [1] 969  NA
    ## 
    ## $convergence
    ## [1] 0

``` r
fit %>% traj.match(method="subplex") -> fit
summary(fit)
```

    ## $params
    ##           K1           K2         N1_0         N2_0           r1 
    ## 180.00000000 100.00000000  10.00000000  10.00000000   0.02666174 
    ##           r2          a12          a21        theta            p 
    ##   0.10734956   0.05763951   0.15195520   0.10028215   0.79771307 
    ## 
    ## $loglik
    ## [1] -291.9524
    ## 
    ## $eval
    ## [1] 3083
    ## 
    ## $convergence
    ## [1] 0
    ## 
    ## $msg
    ## [1] "success! tolerance satisfied"

The maximized likelihood is -291.95. The maximum likelihood estimate (MLE) of the parameters is

``` r
coef(fit) %>% signif(3) %>% as.data.frame()
```

    ##              .
    ## K1    180.0000
    ## K2    100.0000
    ## N1_0   10.0000
    ## N2_0   10.0000
    ## r1      0.0267
    ## r2      0.1070
    ## a12     0.0576
    ## a21     0.1520
    ## theta   0.1000
    ## p       0.7980

To compare the fitted model with the data, we compute and plot the model's trajectory. In doing so, we take care to note that the expected value of the count, given the true abundance, *N*, is *p* *N*. Our estimate of *p* is 0.798.

``` r
trajectory(fit,as.data.frame=TRUE) -> tdat

tdat %>%
  subset(select=-traj) %>%
  melt(id=c("time"),value.name="trajectory",variable.name="species") %>%
  join(dat,by=c("time","species"),type="left") %>%
  ggplot(aes(x=time,group=species,color=species))+
  geom_line(aes(y=coef(fit,"p")*trajectory))+
  geom_point(aes(y=counts))+
  labs(y="counts")
```

![traj1-1](https://user-images.githubusercontent.com/1863307/32173706-35c02d44-bd56-11e7-8b33-f0109295d9af.png)

There is uncertainty associated with the measurement model. We can simulate to quantify this. For example, the following code simulates the measurement model a large number of times, then extracts and plots the median of the simulated data, along with a 95% confidence interval.

``` r
trajectory(fit) -> x

rdply(667,.id="sim",
      rmeasure(fit,x=x,times=time(fit),params=coef(fit)) %>% melt()) %>%
  mutate(species=ifelse(grepl("N1",variable),"N1","N2"),
         time=time(fit)[time]) %>%
  ddply(~time+species,summarize,
        q=c(0.025,0.5,0.975),
        p=quantile(value,prob=q),
        qq=c("lo","med","hi")) %>%
  dcast(time+species~qq,value.var="p") -> quants

quants %>%
  join(dat,by=c("time","species"),type="left") %>%
  ggplot(aes(x=time,color=species,fill=species))+
  geom_point(aes(y=counts))+
  geom_line(aes(y=med))+
  geom_ribbon(aes(ymin=lo,ymax=hi),color=NA,alpha=0.2)
```

![traj2-1](https://user-images.githubusercontent.com/1863307/32173689-2d2c68e6-bd56-11e7-8a4f-e1b958f4d271.png)

[LV_replicated.zip](https://github.com/kingaa/pomp/files/1427598/LV_replicated.zip)

**Comment by murallcl** [comment]
Sorry for the slow reply. Thanks for the updated and more elegant version of the example!! I didn't realise that you could put so many of the functions inside the pomp function. I guess one thing that would be good to include in the example is getting the confidence intervals for each parameter. I'm not sure how to include this given the way you have re-coded it.  For example, in ["introduction to inference"](http://kingaa.github.io/short-course/parest/parest.html#modeling-the-noise), you show how to get CIs for each parameter estimate and plot the log-likelihood function (in the case of estimating more than one parameter). Here:

> To construct confidence intervals—and more generally to visualize the portion of the likelihood surface most relevant to the data—we can construct a profile likelihood for each parameter in turn. To profile over a parameter, we fix the value of that parameter at each of several values, then maximize the likelihood over the remaining unknown parameters.
```
prof2.b <- expand.grid(b=seq(9.6e-5,1.01e-4,length=100))
fitfn <- function (dat) {
  fit <- optim(fn=function(p)f5(c(log(dat$b),logit(p))),
               par=mle1[2],method="Brent",lower=0,upper=1)
  c(p=expit(fit$par),loglik=-fit$value)}
library(plyr)
ddply(prof2.b,~b,fitfn) -> prof2.b
maxloglik <- max(prof2.b$loglik)
plot(loglik~b,data=prof2.b,type="l",ylim=maxloglik+c(-10,0))
cutoff <- maxloglik-qchisq(p=0.95,df=1)/2
abline(h=c(0,cutoff))
abline(v=range(subset(prof2.b,loglik>cutoff)$b),lty=2)
```

Many thanks.

**Comment by kingaa** [comment]
To construct a profile, one simply holds one set of parameters fixed at each point in some grid,and maximizes the likelihood over the remaining parameters.  Thus in the above example, which constructs a profile over the `b` parameter, we first make a grid of values for `b`:
```
prof2.b <- expand.grid(b=seq(9.6e-5,1.01e-4,length=100))
```
Then, we construct a function that, for each value of `b`, will maximize the likelihood over the remaining parameters.  In the above example, this is `fitfn`.  In this example, there is only one remaining parameter, `p`.  In the Lotka-Volterra example, there will be more parameters to maximize over, but the problem is essentially the same.

The call to `ddply` does the profile calculation.

**Comment by murallcl** [comment]
Ok thanks. Here's an example that might better show the trouble I'm having calling things. I use `r1` as the example, and I run it after `summary(fit)` in your code from above.

```
prof.r1 <- expand.grid(r1=seq(1.01e-3,1.01e-1,length=100))
fitfn <- function (dat) {
  fit1 <- optim(fn=function(r2,a12,a21,theta,p)
fit(c(logit(dat$r1),logit(r2),logit(a12),logit(a21),log(theta),logit(p))), #<-don't think that makes sense
                #or use Tp, Tr2, etc from po?
               par=c(fit$params[6],fit$params[7],fit$params[8],fit$params[9],fit$params[10]),
               method="L-BFGS-B",lower=0,upper=1)
  c(r2=expit(fit1$par),loglik=-fit1$value)
  c(a12=expit(fit1$par),loglik=-fit1$value)
  c(a21=expit(fit1$par),loglik=-fit1$value)
  c(theta=expit(fit1$par),loglik=-fit1$value)
  c(p=expit(fit1$par),loglik=-fit1$value)
  }
library(plyr)
ddply(prof.r1,~r1,fitfn) -> prof.r1
```

**Comment by kingaa** [comment]
As before, rather than use `optim` directly, it's better to use `traj.match`.  You just have to leave `r1` out of the list of parameters to estimate (`est`).

Have a look at the ["Getting Started with **pomp**" vignette](http://kingaa.github.io/pomp/vignettes/getting_started.html#maximizing-the-likelihood-by-iterated-filtering) for an example (more complicated because the model is stochastic, but with the same outline.

**Comment by kingaa** [comment]
I'm going to close this issue now, but feel free to reopen it if there is more to discuss.  Also, it would be great to have your example as a vignette in the documentation, to help other users with similar goals.

**Comment by murallcl** [comment]
Hello again, 
I am working on making this example use a pomp model and particle filtering and what I have so far produces some errors that I'm not sure how to fix. 
The code I attach only fits to the means, since I wanted to see if that ran first before including all the replicates per time point. 

The error that I get is after the optim function saying I haven't specified a dmeasure but I believe I have. "Timing stopped at: 0.02 0 0.02, Error : in ‘pfilter’: error in calculation of weights: operation cannot be completed: dmeasure has not been specified"

Also the likelihood surfaces suggest something is wrong and again I'm unsure why. 
Many thanks.
[pompLV_4post.zip](https://github.com/kingaa/pomp/files/2171233/pompLV_4post.zip)

**Comment by kingaa** [comment]
You've given me a very great deal to look at.  Please narrow it down to the pieces that are giving you trouble.

**Comment by murallcl** [comment]
Yes indeed, sorry about that. I went back and in the process of cutting the fat I believe I fixed it. 
I will check the likelihood surfaces and try it with the data with multiple replicates per time point. 
The code is now:

```
#       Example Lotka-Volterra competition model -  pomp model - fitting 2 variables

#libraries:
library(stats4)
library(bbmle)
library(deSolve)
library(ggplot2)
library(gridExtra)

#pomp prelims:
library(pomp)
stopifnot(packageVersion("pomp")>"1.4.9")
library(plyr)
library(reshape2)
options(stringsAsFactors=FALSE)
theme_set(theme_bw())
set.seed(1173439184)

#-----: Data -------
file<-read.csv("simulated_LVcompdata_singlecolumn.csv") 
#get summary of the data
library(lattice)
library(Rmisc)
sumry <-summarySE(data=file, measurevar="counts",groupvars=c("Time","Species"))
#reorganize, new dataframe
sumryN1 <-subset(sumry, Species== "N1")
sumryN2 <-subset(sumry, Species== "N2")
dataset2V<-data.frame("Days"=sumryN1$Time, "avgN1"=sumryN1$counts, "avgN2"=sumryN2$counts)
#fit to averaged data (i.e. only one data point per time point)
```

```
#----------: parameter estimation/fitting (trajectory matching) with pomp ----------------------------
# build pomp object
require(magrittr)
data.frame(t=dataset2V$Days, y1=round(dataset2V$avgN1), y2=round(dataset2V$avgN2)) %>%
  pomp(
    times="t", t0 = 0,
    rmeasure=Csnippet("  
                      y1 = rbinom(N1,rho1);
                      y2 = rbinom(N2,rho2); 
                      "),
    dmeasure=Csnippet("
                      lik = dpois(y1, rho1*N1+1e-6, give_log)+ 
                            dpois(y2, rho2*N2+1e-6, give_log);
                      lik = (give_log) ? lik : exp(lik);
                      "), 

    rprocess = discrete.time.sim(
      step.fun = Csnippet("
                          double t1 = rbinom(N1, 1-exp(-r1*dt));
                          double t2 = rbinom(N1, 1-exp(-r1*N1/K1*dt));
                          double t3 = rbinom(N1, 1-exp(-r1*a12*N2/K1*dt));
                          double t4 = rbinom(N2, 1-exp(-r2*dt));
                          double t5 = rbinom(N2, 1-exp(-r2*N2/K2*dt));
                          double t6 = rbinom(N2, 1-exp(-r2*a21*N1/K2*dt));
                          N1 += t1 - t2 - t3;
                          N2 += t4 - t5 - t6;
                          "), delta.t = 1),
    initializer = Csnippet("
                           N1 = 10;
                           N2 = 10;
                           "),

    toEstimationScale=Csnippet("
                               Tr1 = logit(r1);
                               Tr2 = logit(r2);
                               Ta12 = logit(a12);
                               Ta21 = logit(a21);"),
    fromEstimationScale=Csnippet("
                                 Tr1 = expit(r1);
                                 Tr2 = expit(r2);
                                 Ta12 = expit(a12);
                                 Ta21 = expit(a21);"),
    
    statenames = c("N1","N2"),
    paramnames = c("r1","r2","K1","K2","a12","a21","rho1","rho2")
    ) -> obj

#params to estimate:
toEst <- Csnippet("
                  Tr1 = logit(r1);
                  Tr2 = logit(r2);
                  Ta12 = logit(a12);
                  Ta21 = logit(a21); ")

fromEst <- Csnippet("
                    Tr1 = expit(r1);
                    Tr2 = expit(r2);
                    Ta12 = expit(a12);
                    Ta21 = expit(a21); ")

pomp(obj,
     toEstimationScale=toEst,
     fromEstimationScale=fromEst,
     paramnames=c("r1","r2","a12","a21")) -> comp

coef(comp) <-c(r1=0.1, r2=0.1, K1=150, K2=100, a12=0.4, a21=0.2, rho1=0.9, rho2=0.9)

neg.ll <- function (par, est) {
  allpars <- coef(comp,transform=TRUE)
  allpars[est] <- par
  try(freeze(pfilter(comp, params=partrans(comp, allpars, dir="fromEst"), Np=1000),seed=915909831)
  ) -> pf
  if (inherits(pf,"try-error")) 1e10 else -logLik(pf)}

fit <- optim(
  par=c(log(0.1),log(0.1),log(0.1),log(0.1)), 
  est=c("r1","r2","a12","a21"),
  fn=neg.ll,
  method="Nelder-Mead",
  control=list(maxit=400,trace=0))

mle <- comp
coef(mle,c("r1","r2","a12","a21"),transform=TRUE) <- fit$par
coef(mle)
fit$val

lls <- replicate(n=5,logLik(pfilter(mle,Np=1000)))
ll <- logmeanexp(lls,se=TRUE); ll

#run simulations with these estimated paramters
simulate(mle,nsim=10,as.data.frame=TRUE,include.data=TRUE) -> sims3

#plot data with simulations
ggplot(data=sims3,mapping=aes(x=time,y=y1,group=sim,color=sim=="data"))+
  guides(color=FALSE)+
  geom_line()

ggplot(data=sims3,mapping=aes(x=time,y=y2,group=sim,color=sim=="data"))+
  guides(color=FALSE)+
  geom_line()
```

giving estimates: r1 = 0.0282, r2 = 0.0979, a12 = 0.116, a21= 0.241

![n1_fit](https://user-images.githubusercontent.com/31885778/42412129-beb1b058-8206-11e8-88bc-37188d2ca73a.png)

![n2_fit](https://user-images.githubusercontent.com/31885778/42412134-df31442e-8206-11e8-9efe-cebe87e96c73.png)
