### ISSUE TITLE
obsnames not extracted from data when 1 row in data.frame

### ISSUE THREAD

**Issue by e3bo** [kingaa/pomp#54]
I stumbled upon this problem today when working on tests for the C snippet plugin. Here's an example that shows the problem with pomp 1.15 from CRAN:

    create_example <- function(times = c(1,2), t0 = 0, mu = 0.001, N_0 = 1) {
      data <- data.frame(time = times, reports = NA)
      mmodel <- reports ~ pois(ct)
      rate.fun <- function(j, x, t, params, covars, ...) {
        switch(j, params["mu"]*x["N"], stop("unrecognized event ",j))
      }
      rprocess <- gillespie.sim(rate.fun = rate.fun, v=rbind(N=-1, ct=1), d=rbind(1, 0))
      initializer <- function(params, t0, ...) {
        c(N=N_0,ct=12)
      }
      pomp(data = data, times = "time", t0 = t0, params = c(mu=mu),
        rprocess = rprocess, initializer = initializer,
        zeronames="ct", paramnames=c("mu"), statenames=c("N","ct"),
        measurement.model = mmodel)
     }
     simulate(create_example(times = 1), as.data.frame=TRUE)
     simulate(create_example(times = c(1,2)), as.data.frame=TRUE)

The output from the first simulate call is:

    Error: in ‘simulate’: variable 'reports' not found among the observables

Whereas the second call produces expected output:

       time reports N ct sim
     1    1       0 1  0   1
     2    2       0 1  0   1

The problem seems to be rooted in pomp.R in the line:

    data <- t(sapply(data[-tpos],as.numeric))

The following seems to be a more robust replacement:

    data <- do.call(rbind, lapply(data[-tpos], as.numeric))

**Comment by kingaa** [comment]
Good catch, @e3bo!  I've pushed the fix you provide as version 1.15.1.3.
