### ISSUE TITLE
covar names missing after coercing pomp objects to data frame

### ISSUE THREAD

**Issue by e3bo** [kingaa/pomp#56]
I ran into a little problem today when trying to simulate ensemble distributions at a single time point. It can be demonstrated by adding covariates to the pomp object in the #54:

    library(pomp)

    create_example <- function(times = c(1,2), t0 = 0, mu = 0.001, N_0 = 1,
                                    covar = data.frame(x = c(0, 1), time = c(0, 52))) {
      data <- data.frame(time = times, reports = NA)
      mmodel <- reports ~ pois(ct)
      rate.fun <- function(j, x, t, params, covars, ...) {
          switch(j, params["mu"]*x["N"], stop("unrecognized event ",j))
      }
      rprocess <- gillespie.sim(rate.fun = rate.fun, v=rbind(N=-1, ct=1))
      initializer <- function(params, t0, ...) {
         c(N=N_0,ct=12)
      }
      pomp(data = data, times = "time", t0 = t0, params = c(mu=mu),
                rprocess = rprocess, initializer = initializer,
                zeronames = "ct", paramnames = "mu", statenames = c("N","ct"),
                measurement.model = mmodel, covar = covar, tcovar = "time")
    }
    simulate(create_example(times = 1), as.data.frame=TRUE)
    simulate(create_example(times = c(1,2)), as.data.frame=TRUE)

With pomp 1.15.3.1 (current master branch on github), I get the following output:

      time reports N ct         NA sim
    1    1       0 1  0 0.01923077   1

whereas the second example is fine:

      time reports N ct          x sim
    1    1       0 1  0 0.01923077   1
    2    2       0 1  0 0.03846154   1

The output with missing variable names can lead to cryptic error messages when used in a pipe with some `dplyr` functions. In case it's of use, my solution was to change `lookup_in_table` like this: e3bo/pomp@72741ae63d1cb1bf63c87f7ef614b7a5d894785d .

**Comment by kingaa** [comment]
Thanks for this, @e3bo.  Although your fix is clean and goes to the root of the matter, I'm a bit reluctant to change the behavior of `lookup_in_table` in that way.  My concern is a small one. The main use-case for `lookup_in_table` in practice is in `init.state`, where the covariate at a single value is requested.  There will be a very slight cost to creating the more complex object in this case, but this cost may be incurred many times over the course of an extensive computation.  At any rate, such is my reasoning in support of the uglier fix I've applied, which is to change the behavior in the `coerce`-to-data-frame method for pomps.
