### ISSUE TITLE
How can I include a vector of covariates in dmeasure or rmeasure in a C snippet?

### ISSUE THREAD

**Issue by rubbislam** [kingaa/pomp#60]
Hi. I try to include some covariates that are vectors obviously to calculate the likelihood with some time lags. I've read FAQ 3.1 but in that example, but that example only mentions how to include vector states variables in `rprocess`. 

I used similar trick to include the covariates in dmeasure and add covar in `pomp()` function, but I get error:
`error: variable-sized object may not be initialized`

Thanks.

**Comment by kingaa** [comment]
@rubbislam: Sorry to take so long to respond.  

Inclusion of vector covariates is indeed very similar to inclusion of vectors in states or observations, so you must be making some mistake.  Can you provide a minimal example of the problem?  Is the error arising when you call `pomp`, or when you do something with a constructed pomp object?
 
In responding, please read and follow the instructions in the second paragraph of [FAQ 1.1](https://kingaa.github.io/pomp/FAQ.html#effective-request).

**Comment by rubbislam** [comment]
@kingaa Thanks a lot. 

I reviewed the code and FAQ 3.1 carefully and figured out what the problem was. I defined the names of the vectors as same as those of the covariates, which caused conflicts. 

I'm closing this issue.

**Comment by rubbislam** [comment]
I wonder how to use the values in former time of states and covariates in dmeasure. It seems `*x = &X` gets only the values of different states, but what if we need the vector of the specified state of all time?

Here is the code:

- rmeas: Y ~ rnorm(X, 2)
- dmeas: dnorm(X[t], X[t-1], A[t-1], give_log)
- rprocess: X[t] = rnorm(X[t-1],A[t-1])

```
rproc <- Csnippet("
  X = rnorm(X,A*K);
")

rmeas <- Csnippet("
  Y = rnorm(X, 2);
")

dmeas <- Csnippet("
  double *x = &X;
  double *a = &A;
  int m = (int) t;
  lik = dnorm(x[m-1], x[m-2], a[m-2], give_log);
")

dat <- data.frame(time=1:20, Y=rnorm(20,0,2))
covar <- data.frame(time=0:20, A=abs(rnorm(21,0,1)))

p <- pomp(data=dat,
          times="time",
          t0=0,
          rprocess=euler.sim(rproc, delta.t=1),
          statenames="X",
          paramnames="K",
          covar=covar,
          tcovar="time",
          params=c(K=2),
          dmeasure=dmeas,
          rmeasure=rmeas,
          initializer=function(params, t0, ...) {
            x0 <- c(X=0)
            x0
          }
          )

y <- simulate(p,params=c(K=2),nsim=10,as.data.frame=TRUE)
ggplot(data=y,mapping=aes(x=time,y=Y,group=sim)) +
  geom_line() + theme_classic()
pf <- pfilter(p,params=c(K=2),Np=1)
plot(pf)
```

And here're the session information:

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] R.matlab_3.6.1 ggplot2_2.2.1  reshape2_1.4.3 magrittr_1.5   pomp_1.16     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15      munsell_0.4.3     colorspace_1.3-2  lattice_0.20-35   rlang_0.1.6       subplex_1.4-1    
 [7] stringr_1.2.0     plyr_1.8.4        tools_3.4.3       grid_3.4.3        gtable_0.2.0      R.oo_1.21.0      
[13] coda_0.19-1       lazyeval_0.2.1    digest_0.6.14     tibble_1.4.2      nloptr_1.0.4      R.utils_2.6.0    
[19] deSolve_1.20      labeling_0.3      stringi_1.1.6     compiler_3.4.3    pillar_1.1.0      scales_0.5.0     
[25] R.methodsS3_1.7.1 mvtnorm_1.0-7  
```


Thanks.

**Comment by kingaa** [comment]
@rubbislam:  Interesting question.  There is a reason that the states and observations at previous times are not accessible to you.  This has to do with the basic structure of a partially observed Markov process.  It is part of the definition of this class of models that the observations at a given time depend only on the state at that time.  Moreover, it is necessary that the latent state process be first-order Markovian.  See [the JSS paper](http://kingaa.github.io/pomp/vignettes/pompjss.pdf) and [the SISMID lecture notes](https://kingaa.github.io/sbied/intro/intro.html#partially-observed-markov-process-pomp-models) for more formal and detailed descriptions.  If users were given access to the previous states, it would enable them to implement models for which the inferences **pomp** affords are invalid.

It is worth noting, however, that it is often possible to turn a higher-order latent state process into a first order Markovian process.

In the codes you provide, I don't understand what you are trying to do.  Firstly, the model specifications,

> rmeas: Y ~ rnorm(X, 2)
> dmeas: dnorm(X[t], X[t-1], A[t-1], give_log)
> rprocess: X[t] = rnorm(X[t-1],A[t-1])

are ambiguous. For example, I think the usage of `rnorm` is unclear and your `dmeas` does not correspond to your `rmeas`.  In fact, your `dmeas` does not even depend on the data.  Until I can understand what you are trying to accomplish, it is difficult to give more specific advice.

**Comment by rubbislam** [comment]
I am trying to reproduce the results of [Rasmussen et al.](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002136) using iterated filtering instead of particle MCMC, according to their published [code](http://sites.duke.edu/koelle/files/2013/08/pmcmcsourcecode.zip).

Actually, the results were reproduced by using extra .C file, combined with rprocess and dmeasure written in R functions in POMP. However, this method costs an extremely long time to go through the iterations. So I wonder whether we can just write the rprocess and dmeasure in C snippet to save the computational time.

```
library(pomp)

## --------------- Setup The System ---------------------------
rmeas <- Csnippet("
  cases = rnorm(rho*incid, sqrt(tau*rho*incid));
")

rprocess <- Csnippet("
  int nrate = 6;
  double rate[nrate], trans[nrate];
  double beta;
  double dW = rnorm(0,1)/sqrt(dt);
  double P = S + I + R;
 
  beta = R0*(gamma + mu)*(1 + alpha*cos(M_2PI*(t/12-floor(t/12))));
  
  rate[0] = mu * P;                   // birth
  rate[1] = beta * (1+F*dW)*I/P;      // force of infection
  //rate[1]=(rate[1]>0?rate[1]:0);
  rate[2] = mu;                             // death from S
  rate[3] = gamma;                          // recovery
  rate[4] = mu;                             // death from I
  rate[5] = mu;                             // death from R
  S=(S>0?S:0);
  I=(I>0?I:0);
  R=(R>0?R:0);

  trans[0] = rpois(rate[0]*dt);
  reulermultinom(2, S, &rate[1], dt, &trans[1]);
  reulermultinom(2, I, &rate[3], dt, &trans[3]);
  reulermultinom(1, R, &rate[5], dt, &trans[5]);

  S += trans[0] - trans[1] - trans[2];
  I += trans[1] - trans[3] - trans[4];
  R += trans[3] - trans[5];
  incid += trans[1];
  S=(S>0?S:0);
  I=(I>0?I:0);
  R=(R>0?R:0);
  P = S + I + R;
")

skel <- Csnippet("
  int nrate = 6;
  double rate[nrate], term[nrate];
  double beta;
  double P = S + I + R;
  beta = R0*(gamma + mu)*(1 + alpha*cos(M_2PI*(t/12-floor(t/12))));

  rate[0] = mu * P;                   // birth
  rate[1] = beta*I/P;                 // force of infection
  rate[2] = mu;                             // death from S
  rate[3] = gamma;                          // recovery
  rate[4] = mu;                             // death from I
  rate[5] = mu;                             // death from R

  term[0] = rate[0];
  term[1] = rate[1]*S;
  term[2] = rate[2]*S;
  term[3] = rate[3]*I;
  term[4] = rate[4]*I;
  term[5] = rate[5]*R;

  DS = term[0] - term[1] - term[2];
  DI = term[1] - term[3] - term[4];
  DR = term[3] - term[5];
  Dincid = term[1];
")

fromlog <- Csnippet("
  TR0 = exp(R0);
  Tgamma = exp(gamma);
  Tmu = exp(mu);
  Talpha = exp(alpha);
  TF = exp(F);
  Trho = expit(rho);
  Ttau = exp(tau);
  from_log_barycentric (&TS_0, &S_0, 3);
")

tolog <- Csnippet("
  TR0 = log(R0); 
  Tgamma = log(gamma);
  Tmu = log(mu);
  Talpha = log(alpha);
  TF = log(F);
  Trho = logit(rho);
  Ttau = log(tau);
  to_log_barycentric (&TS_0, &S_0, 3);
")
```

The likelihood depends on two part: one is the time series and another is the genealogy. And the genealogy likelihood relates to the the susceptible and infectious, population size, as well as the lineages in previous sub time intervals. And here's the `dmeasure` function:

```
dmeas <- Csnippet("
  double beta, lambda, prob_coal, prob_no_coal, lik_ts;
  double *s = &S, *i = &I, *r = &R;
  double pop, sub_t;
  const double *et = get_pomp_userdata_double(\"event_time\");
  const double *idx = get_pomp_userdata_double(\"indices\");
  const double *ce = get_pomp_userdata_double(\"coal_event\");
  const double *L = get_pomp_userdata_double(\"lineages\");
  const double *ref = get_pomp_userdata_double(\"dt_ref\");
  int m = (int) t;
  int N = idx[m] - idx[m-1];
  for (int k=0; k<N; k++) {
    int ind = (int) idx[m-1] - 1 + k;
    beta = R0*(gamma+mu)*(1+alpha*cos(M_2PI*(et[ind]/12-floor(et[ind]/12))));
    pop = s[ref[ind]] + i[ref[ind]] + r[ref[ind]];
    int re = (int) ref[ind] - 1;
    lamdba = L[ind]*(L[ind]-1)/(i[re]*i[re])*beta*s[re]*i[re]/pop;
    sub_t = et[ind] - et[ind-1];
    prob_coal = lambda*exp(-lambda*sub_t);
    prob_no_coal = exp(-lambda*sub_t);
    if (k<1)
      lik_gene = 1;
    else
      lik_gene = lik_gene * (prob_coal*ce[ind-1] + prob_no_coal*(1-ce[ind-1]));
  }
  if (ISNAN(lik_gene)||ISNA(lik_gene)||lik_gene==0||!R_FINITE(lik_gene))
    lik_gene = 2.225074e-308;  //.Machine$double.xmin

  lik_ts = dnorm(cases, rho*incid, sqrt(tau*rho*incid), give_log);
  lik = (give_log)? (log(lik_gene)+lik_ts) : (lik_gene*lik_ts);
")
```
Since `*a=&A` cannot access value in previous time, I use `get_pomp_userdata_double` to access covariate instead of setting them in `covar` and `tcovar` argument in `pomp`.

```
## --------------- Load Data -------------------------------------
dataG <- read.csv("covar.csv", header=TRUE, as.is=TRUE)
event_time <- dataG$event_time
coal_event <- dataG$coal_event
lineages <- dataG$lineages
dt_ref <- dataG$dt_ref
indices <- read.csv("indices.csv", header=TRUE, as.is=TRUE)
indices <- indices[,1]
mockdata <- read.csv("mockdata.csv", header=TRUE, as.is=TRUE)

## ------------------ Setup POMP --------------------------------------
guess <- c(gamma=3, R0=10, alpha=0.16, F=0.012, mu=0.0012, popsize=1e6,
           tau=15, rho=0.43, S.0=0.1, I.0=357/1e6, R.0=0.9-357/1e6)

po <- pomp(name="Rasmussen.Mock",
           data=mockdata,
           times="time",
           t0=0,
           dmeasure=dmeas,
           rmeasure=rmeas,
           rprocess=euler.sim(step.fun=rprocess, delta.t=0.01),
           skeleton=skel,
           fromEstimationScale=fromlog,
           toEstimationScale=tolog,
           statenames=c("S", "I", "R", "incid"),
           paramnames=c("R0", "gamma", "mu", "alpha", "F", 
                        "rho", "tau", "popsize", 
			 "S.0", "I.0", "R.0"),
           params=guess,
           zeronames=c("incid"),
           comp.names=c("S", "I", "R"),
           ic.names=c("S.0", "I.0", "R.0"),
           initializer=function(params, t0, comp.names, ic.names, ...){
             x0 <- numeric(4)
             names(x0) <- c("S","I","R","incid")
             fracs <- params[ic.names]
             fracs<-ifelse(fracs>0,fracs,0)
             fracs<-fracs/sum(fracs)
             x0[comp.names] <- round(params['popsize']*fracs/sum(fracs))
             x0
           }
)
```

I've used the `simulate` function to test the `rmeasure` and `rprocess`, both of which are fine and consistent with the paper results. Please find attached data.

[data.zip](https://github.com/kingaa/pomp/files/1702496/data.zip)
