### ISSUE TITLE
Custom distributions: Dirichlet in C snippet

### ISSUE THREAD

**Issue by gcgibson** [kingaa/pomp#61]
I was wondering how I can include a custom distribution inside a C snippet? I was hoping to use a dirichlet distribution for the parameters of a State Space model and perform top level inference using PMCMC on a dirichlet. 

Thanks!

**Comment by kingaa** [comment]
You'll just need to include definitions for the operative bits (probably density calculations and/or samplers) in the C code.  You can include these inside the C snippets you write, or you can use the `global` argument to `pomp` (the pomp-object construction function) to make top-level function declarations.  In general, anything that you can do in C can be done in a C snippet.

**Comment by gcgibson** [comment]
@kingaa Awesome! Can you give me an example? Sorry I am pretty dense with C. Would it not be easier to just run the model using gcc?

**Comment by kingaa** [comment]
Take a look at the examples in the 'pomp.h' header file.  There are several: for multinomial, beta-binomial, beta-negative binomial, and Euler-multinomial distributions.

As for "running the model using gcc", I'm not sure what you mean.  If you mean writing custom stand-alone code in C, I suspect not.
