### ISSUE TITLE
pomp.h file not found

### ISSUE THREAD

**Issue by rayleigh** [kingaa/pomp#62]
I've successfully installed `pomp` using `install.packages()` and `devtools()`. However, I get the following error when I try running pomp:

```
pomp(
+     data=data.frame(time=1:50,Y=NA),
+     times="time",
+     t0=0,
+     rmeasure=Csnippet('
+                       Y = rlnorm(log(X),tau);
+                       '),
+     dmeasure=Csnippet('
+                       lik = dlnorm(Y,log(X),tau,give_log);
+                       '),
+     rprocess=discrete.time.sim(
+         step.fun=Csnippet('
+                           double S = exp(-r*dt);
+                           double eps = rlnorm(0,sigma);
+                           X = pow(K,(1-S))*pow(X,S)*eps;
+                           '),
+         delta.t=1
+         ),
+     paramnames=c("sigma","tau","r","K"),
+     statenames="X",
+     params=c(r=0.1,K=1,sigma=0.1,tau=0.1,X.0=1)
+     )
/var/folders/t_/1_x0_5md5d738c6m7hz7hjf40000gn/T//RtmpNRrSrK/7671/pomp_921cff2c1e26f782d84c25594764925a.c:4:10: fatal error: 'pomp.h' file not found
#include <pomp.h>
         ^~~~~~~~
1 error generated.
make: *** [/var/folders/t_/1_x0_5md5d738c6m7hz7hjf40000gn/T//RtmpNRrSrK/7671/pomp_921cff2c1e26f782d84c25594764925a.o] Error 1
Error: in ‘pomp’: error in building shared-object library from C snippets: in ‘pompCBuilder’: compilation error: cannot compile shared-object library ‘/var/folders/t_/1_x0_5md5d738c6m7hz7hjf40000gn/T//RtmpNRrSrK/7671/pomp_921cff2c1e26f782d84c25594764925a.so’: status = 1
```

However, when I run the C test script, I get the following results:
```
source("https://kingaa.github.io/scripts/helloC.R",echo=TRUE)

> try({
+     cat("#include <R.h>
+      void hello (void) {
+      Rprintf(\"\\\n\\n\\nHello from native C!\\n\\n\\n\");
+      }",file="helloC.c")
+ .... [TRUNCATED] 
clang -I/Library/Frameworks/R.framework/Resources/include      -I/usr/local/include  -g -O2 -fPIC  -Wall -g -O2  -c helloC.c -o helloC.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o helloC.so helloC.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


Hello from native C!


[1] TRUE TRUE TRUE
```

If I try making the C file myself (rename the pomp.so file as libpomp.so), I get the following error:
```
gcc /var/folders/t_/1_x0_5md5d738c6m7hz7hjf40000gn/T//RtmpDE15Tg/452/pomp_1283b8e523341c1c397a051df9fc062e.c -I/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pomp/include/ -I/Library/Frameworks/R.framework/Resources/include -L/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pomp/libs/ -lpomp
Undefined symbols for architecture x86_64:
  "_R_RegisterCCallable", referenced from:
      _R_init_pomp_1283b8e523341c1c397a051df9fc062e in pomp_1283b8e523341c1c397a051df9fc062e-41523c.o
  "_Rf_dlnorm", referenced from:
      ___pomp_dmeasure in pomp_1283b8e523341c1c397a051df9fc062e-41523c.o
  "_Rf_rlnorm", referenced from:
      ___pomp_rmeasure in pomp_1283b8e523341c1c397a051df9fc062e-41523c.o
      ___pomp_stepfn in pomp_1283b8e523341c1c397a051df9fc062e-41523c.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
From this and checking, `pomp.h` is in `/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pomp/include/`.

My Mac is using High Sierra and R 3.4.4. I appreciate any help debugging this issue.

**Comment by kingaa** [comment]
Thanks for posting the issue!  It appears that `R CMD SHLIB` is not able to find the `pomp.h` header.  One possibility is that this complication, not seen in OS X versions <=10.12, arises anew in 10.13 (High Sierra).  However, I have just tested the package on OS X 10.13 and everything checks out fine.   So a working hypothesis is that something is not quite right about your particular build.  Let's try to debug this.

I [assume you're using the latest version of **pomp**](http://kingaa.github.io/pomp/FAQ.html#effective-request)?

Could you do the following and post the results?  

1. In an **R** session, build the C file for the pomp object.  You accomplish this via the usual call to `pomp`, but you tell `pomp` to write the C code into a file of your choice using the `cdir` and `cfile` arguments.  Your call (in an **R** session) will look something like
```
pomp(...,cdir=getwd(),cfile="myexample")
```
where the `...` stands for all the usual arguments you've used above.

2. Find out where the `pomp.h` header is installed.  It looks like you've found it already, but if you haven't, or if the library that **R** is actually using is different, do the following in an **R** session:
```
system.file("include",package="pomp")
```

3. Build the shared-object library.  The way you've done this above is not correct. The proper way to do it is to use `R CMD SHLIB`.  Thus, at the terminal command line, do:
```
R CMD SHLIB -I /path/to/installed/pomp/library/include/ myexample.c
```
The path given to the `-I` flag should match the output of the `system.file` call above.

4. Now, to test the compilation one more time, remove the `myexample.so` and `myexample.o` files and try to call `R CMD SHLIB` from inside **R**:
```
file.remove(c("myexample.o","myexample.so"))
cflags <- paste0("PKG_CFLAGS=\"","-I",system.file("include",package="pomp"),"\"")
system2(command=R.home("bin/R"),args=c("CMD","SHLIB","myexample.c"),env=cflags)
```

**Comment by rayleigh** [comment]
Hi,

Thanks for responding and for your advice; I apologize for my delayed response. I looked at Github, but because this issue showed only one comment, it didn't seem as if you had responded until I clicked on the issue again today.

1) I get the following error:

```
make: *** No rule to make target `Prices/myexample.o', needed by `/Users/moby/Documents/Michigan/Research/Housing'.  Stop.
Error: in ‘pomp’: error in building shared-object library from C snippets: in ‘pompCBuilder’: compilation error: cannot compile shared-object library ‘/Users/moby/Documents/Michigan/Research/Housing Prices/myexample.so’: status = 1
```

2) It can be found here:

```
"/Users/moby/Library/R/3.4/library/pomp/include"
```

3) I get the following error:

```
make: *** No rule to make target `Prices/myexample.o', needed by `Prices/myexample.so'.  Stop.
```

4) I get the following output:

```
clang -I/Library/Frameworks/R.framework/Resources/include      -I/usr/local/include  -g -O2 -fPIC  -Wall -g -O2  -c myexample.c -o myexample.o
myexample.c:4:10: fatal error: 'pomp.h' file not found
#include <pomp.h>
         ^~~~~~~~
1 error generated.
make: *** [myexample.o] Error 1
```

However, cflags looks like it's set correctly because it's the following:
```
"PKG_CFLAGS=\"-I/Users/moby/Library/R/3.4/library/pomp/include\""
```

Thanks again for your help and I apologize again for my delayed response.

**Comment by kingaa** [comment]
My turn to apologize.  I've been traveling.  This is very strange behavior, since the header file exists and is on the path, yet is not being found.  Are you here at UM?  If so, perhaps it would be most efficient were we to get together to debug this.  We could also do a video conference, if you prefer.

**Comment by kingaa** [comment]
Great!  We found the problem.  The global user `Makevars` file (`~/.R/Makevars`) was setting the environment variable `PKG_CFLAGS`.  This overrode **pomp**'s setting of the same environment variable, which made it impossible for `R CMD SHLIB` to find the `pomp.h` header file.

The solution was to remove the `Makevars` file or to comment out the `PKG_CFLAGS` setting.  Once this is done, compilation works out of the box.
