### ISSUE TITLE
Relaxing the Markov property

### ISSUE THREAD

**Issue by MarieAugerMethe** [kingaa/pomp#64]
Hello Aaron and all,

I’m completely new to POMP, so sorry if this is a silly novice question. I am writing a state-space model where the state at time t depends not only on the state at time t-1 but also on the state at time t-2.  I’ve been going through the tutorials and realized that the functions for the rprocess don’t specify the time of the state variable.  So for example, if I write:

```
ss_step <- Csnippet('
  double step_x = 0.0;
  step_x = rnorm(0, sigma_state);
  state_x = state_x + step_x;
')
```

It’s assumed that the state at time t depends on t-1, and is:
x_t = x_{t-1} + epsilon,    epsilon ~ N(0, sigma)

But I would like, something like:
x_t = x_{t-1} + rho*(x_{t-1} – x_{t-2}) + epsilon,  epsilon ~ N(0, sigma)

Is it possible? How would I write this?

Many thanks,

Marie

**Comment by tomessilva** [comment]
There's a simple way of converting any order-1 Markov process to order-2...
you just have to expand the state:

epsilon ~ N(0, sigma)
x_t = x_{t-1} + rho*(x_{t-1} – y_{t-1}) + epsilon
y_t = x_{t-1}

Now your state is (x_t,y_t) and your transition function only depends on
the current state.

You can do this to have a Markov chain of arbitrary order... you just need
to carry more "history" in your state.

On Mon, May 7, 2018 at 10:26 PM, Marie Auger-Methe <notifications@github.com

**Comment by MarieAugerMethe** [comment]
Thank you @tomessilva,

I was actually thinking about doing this, but when I tried it didn't quite work because of how I ordered variables. But you are right, if I keep track of things properly, it works. 

```
ss_step <- Csnippet('
  double step_x = 0.0;
  double step_x_temp = state_x;
  step_x = rnorm(0, sigma_state);
  state_x = state_x + rho*(state_x - state_xm1) + step_x;
  state_xm1 = state_x_temp;
')
```

Thanks!
