### ISSUE TITLE
problem with C snippets

### ISSUE THREAD

**Issue by stevenhuyi** [kingaa/pomp#67]
Hi, everyone
Recently, I get started to learn and use the pomp package in my research, but encounter a problem I'm struggling with, that is I am not able to use C sinppets.  I've done what's told in installation instructions and follow what are told in  FAQ 3, but it still cannot work. when running a pomp class with C sinppets, the following errors emerge:
[2](https://user-images.githubusercontent.com/39373773/40177355-e510c470-59cd-11e8-8a23-ecc40f1b1d53.jpg)
and here is the version information:
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pomp_1.16.2.3 sp_1.2-5     

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  deSolve_1.21    subplex_1.5-4   tools_3.4.1     coda_0.19-1    
 [6] mvtnorm_1.0-7   grid_3.4.1      digest_0.6.15   nloptr_1.0.4    lattice_0.20-35

Would you please help me out? Thanks

Yi

**Comment by kingaa** [comment]
@stevenhuyi 

FAQ 3 doesn't deal with this problem.  Did you mean to refer to [FAQ 4.2](https://kingaa.github.io/pomp/FAQ.html#why-cant-i-run-csnippets)?

I assume you've tried the "hello world" script recommended in FAQ 4.2 and received the same failure-to-compile error.

This points to a problem with your installation of **Rtools**, the additional utilities that are needed to compile shared-object libraries on Windows systems.  Please check your installation of **Rtools**.  You can see these instructions on the [installation instructions page](https://kingaa.github.io/pomp/install.html#important-note-for-windows-users). In particular, make sure you install a version of **Rtools** that corresponds to your version of **R** and that you tick the appropriate boxes during the installation of  **Rtools**.

If problems persist, try installing different versions of **Rtools**: I have had the experience that not all versions of **Rtools** that are listed as compatible with my version of **R** actually work.  As of this writing, for instance, I see two versions of **Rtools** that are listed as compatible with your version of **R**.  If one fails, try the other.

Finally, if this does not solve your problem, try running the following line in the same directory you were in before and posting the output:
```
source("https://kingaa.github.io/scripts/diagnostics.R")
```

**Comment by stevenhuyi** [comment]
Thanks a lot, Dr. King. It has been resolved. It works after ticking the “edit system PATH” box when reinstalling Rtools. It's my carelessness. Thanks again. @kingaa
