### ISSUE TITLE
Measles example

### ISSUE THREAD

**Issue by adesupo** [kingaa/pomp#77]
while trying out the measles example, i keep getting the error message below. kindly clarify. thanks.

Error: in ‘pomp’: error in building shared-object library from C snippets: in ‘pompCBuilder’: compilation error: cannot compile shared-object library ‘C:/Users/user/AppData/Local/Temp/RtmpWMBohu/6992/pomp_d6bbffe75be784fe9c3cb1781052dfea.dll’: status = 1
compiler messages:
Warning messages:
1: running command 'make -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB="C:/Users/user/AppData/Local/Temp/RtmpWMBohu/6992/pomp_d6bbffe75be784fe9c3cb1781052dfea.dll" WIN=64 TCLBIN=64 OBJECTS="C:/Users/user/AppData/Local/Temp/RtmpWMBohu/6992/pomp_d6bbffe75be784fe9c3cb1781052dfea.o"' had status 127 
2: running command 'make -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" SHLIB="C:/Users/user/AppData/Local/Temp/RtmpWMBohu/6992/pomp_d6bbffe75be784fe9c3cb1781052dfea.dll" WIN=64 TCLBIN=64 OBJECTS="C:/Users/user/AppData/Local/Temp/RtmpWMBohu/6992/pomp_d6bbffe75be784fe9c3cb1781052dfea.o" shlib-clean' had s
In addition: Warning message:
running command '"C:/PROGRA~1/R/R-33~1.3/bin/R" PKG_CPPFLAGS="-IC:/Users/user/Documents/R/win-library/3.3/pomp/include" CMD SHLIB -c -o C:/Users/user/AppData/Local/Temp/RtmpWMBohu/6992/pomp_d6bbffe75be784fe9c3cb1781052dfea.dll C:/Users/user/AppData/Local/Temp/RtmpWMBohu/6992/pomp_d6bbffe75be784fe9c3cb1781052dfea.c' had status 1

**Comment by kingaa** [comment]
FAQ 4.2.  FAQ 1.1.
