### ISSUE TITLE
Cannot run mif2 on BBS example

### ISSUE THREAD

**Issue by tilling** [kingaa/pomp#8]
Has anyone ever run mif2 on the BBS example? pfilter works, but not mif2. 
The error message is
```
Error: in ‘mif2’: particle-filter error:Error : ‘mif2.pfilter’ error: ‘dmeasure’ returns non-finite value
```
which might have to do with the fact that the variable S is almost entirely missing.

If anyone has actually run this before, I would be grateful to see the code.

**Comment by kingaa** [comment]
```
require(pomp)
packageVersion("pomp")
pompExample(bbs)
mif2(bbs,Np=1000,rw.sd=rw.sd(beta=0.01,sigma=0.01),transform=TRUE,
        Nmif=100,cooling.fraction=0.9) -> mf
plot(mf)
```

Perhaps the problem you encountered was to do with failure to specify `transform=TRUE`.  The default behavior, which adds the random-walk perturbations on the natural scale, results therefore, from time to time, in negative values of the parameters, hence undefined likelihood.  See also [FAQ 4.1](https://kingaa.github.io/pomp/FAQ.html#non-finite-dmeasure).
