### ISSUE TITLE
Stochastic simulation reproducibility with seed: only works when number of repeated sims and number of parameter sets is exactly the same

### ISSUE THREAD

**Issue by luccoffeng** [kingaa/pomp#81]
Hi! Great work on pomp, I'm very excited to work with it! As I was checking reproducibility of my stochastic simulations with `pomp2::simulate()`, I noticed that I cannot reproduce a particular stochastic simulation on its own when the original was run as part of a batch generated by means of a single call to `simulate()` with `nsim > 1` and/or number of parameter sets >1. To demonstrate, I use the SIR model code that is provided as an example on the pomp website (R script attached).

[test_pomp_rns.R](https://github.com/kingaa/pomp/files/2784801/test.pomp.rns.r.txt)

**Comment by luccoffeng** [comment]
To clarify: I can reproduce an entire batch of simulations!

**Comment by kingaa** [comment]
I'm not sure what your expectation is.  For example, in your `test.seed` function, you supply a vector of seeds.  Do you anticipate there will be a mapping between these and the individual simulations?  In fact, only the first element of this vector is meaningful.

Also, you should note that the when more than one simulation is requested (nsim > 1 or number of parameter sets > 1), these are not produced sequentially.  Rather, the simulations are produced as an ensemble, and the process simulations are performed before the measurement-model simulations.

Perhaps, if you explain what you are trying to do, I can suggest a way to accomplish it.

**Comment by luccoffeng** [comment]
Thanks for the prompt response. I was checking reproducibility, and as a test, I wanted to reproduce a single stochastic simulation that was originally produced as part of a larger batch of repeated simulations (nsim > 1 and/or multiple parameter sets). Indeed I was anticipating that the seeds would be mapped to individual simulations and/or parameter sets. I did not receive a warning that only the first element of the seed vector would be used. 

I was not aware that simulations are not performed sequentially, which explains the behaviour that caught my attention. They behaviour seemed alarming to me as I could not explain it and therefore wasn't sure whether there might be other situations for which my work would not be reproducible. Thanks for clarifying!

**Comment by kingaa** [comment]
Perhaps it is worth putting in a warning when seeds of length > 1 are furnished.  I assume you understand that this in no way compromises reproducibility.
