### ISSUE TITLE
"error in building shared-object library from C snippets"

### ISSUE THREAD

**Issue by danieljn19** [kingaa/pomp#82]
Hi, I am having issues running a model with POMP that worked correctly months ago. I am getting the following error. Is there something that needs to be updated? Thanks!

Error: in ‘pomp’: error in building shared-object library from C snippets: in ‘Cbuilder’: compilation error: cannot compile shared-object library ‘/var/folders/rq/vc780bh916525yh64ph_01780000gn/T//RtmpcflSdl/22756/pomp_38c2578465b57ff95b860921fd5705e7.so’: status = 1
compiler messages:
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Library/Frameworks/R.framework/Versions/3.5/Resources/library/pomp/include -I/Users/macbookpro/Documents/Research/Biological Rhythms Modeling Project/code  -I/usr/local/include   -fPIC  -Wall -g -O2  -c /var/folders/rq/vc780bh916525yh64ph_01780000gn/T//RtmpcflSdl/22756/pomp_38c2578465b57ff95b860921fd5705e7.c -o /var/folders/rq/vc780bh916525yh64ph_01780000gn/T//RtmpcflSdl/22756/pomp_38c2578465b57ff95b860921fd5705e7.o
clang: error: no such file or directory: 'Rhythms'
clang: error: no such file or directory: 'Modeling'
clang: error: no such file or directory: 'Project/code'
make: *** [/var/folders/rq/vc780bh916525yh64ph_01
In addition: Warning message:
In system2(command = R.home("bin/R"), args = c("CMD", "SHLIB", "-c",  :
  running command 'PKG_CPPFLAGS="-I/Library/Frameworks/R.framework/Versions/3.5/Resources/library/pomp/include -I/Users/macbookpro/Documents/Research/Biological Rhythms Modeling Project/code" '/Library/Frameworks/R.framework/Resources/bin/R' CMD SHLIB -c -o /var/folders/rq/vc780bh916525yh64ph_01780000gn/T//RtmpcflSdl/22756/pomp_38c2578465b57ff95b860921fd5705e7.so /var/folders/rq/vc780bh916525yh64ph_01780000gn/T//RtmpcflSdl/22756/pomp_38c2578465b57ff95b860921fd5705e7.c 2>&1' had status 1

**Comment by kingaa** [comment]
> clang: error: no such file or directory: 'Rhythms'
> clang: error: no such file or directory: 'Modeling'
> clang: error: no such file or directory: 'Project/code'
