### ISSUE TITLE
Error: bad option for ‘covar’.

### ISSUE THREAD

**Issue by danieljn19** [kingaa/pomp#83]
Hi, I receive the following error when I enter my model.pomp.object line. This is after updating my pomp package (pomp2). 

in ‘pomp’: the unrecognized argument ‘tcovar’ is available for use by the POMP basic components.
Error: bad option for ‘covar’.

**Comment by kingaa** [comment]
See the upgrade guide.  There is a section on [covariates](http://kingaa.github.io/pomp/vignettes/upgrade_guide.html#covariates).
