### ISSUE TITLE
How to implement a Multidimensional model in POMP to use enkf

### ISSUE THREAD

**Issue by marius190** [kingaa/pomp#84]
Hi,

I am not able to use enkf, because it looks like does not allow multi-dimensional Xt variables. I recieve an error saying "Error in c(0, 1) %*% x : non-conformable arguments"

Also when defining x.0 on the parameter vector is not possible to define it as a vector. 

```
### Non Harmonic oscillator example

## Simulation
iter=100 # Data length
g=7 # Variance of noise
omega=0.035 
lambda=0.003
x=matrix(nrow=iter,ncol=2)
y=numeric(iter)
x[1,]=c(1,0) #+rnorm(1,0,0.2)
y=x[1,1]+rnorm(1,0,g)
dt=1:iter
for (i in 2:iter){
  Mk=c(2+omega^2-lambda^2*x[i-1,1]^2,1,-1,0)
  Mk=matrix(Mk,nrow=2)
  x[i,]=Mk%*%x[i-1,]
  y[i]=x[i,1]+rnorm(1,0,g)
}
h <- function(x){c(1,0)%*%x} ### The function fail here. 
R=g #sig_0^2
OscilatorData=data.frame(cbind(dt,y))
colnames(OscilatorData)=c("Time","Y")
#plot(y,type="l")

# X process
oscilator.proc.sim <- function(x,t, params, delta.t,...){
  Mk=c(2+params["omega"]^2-params["lambda"]^2*x[1]^2,1,-1,0)
  Mk=matrix(Mk,nrow=2)
  #print(x)
  #x=Mk%*%x # El x que mete aqui da por es de long. uno
  x=matrix(c(Mk[1,1]*x[1]+Mk[1,2]*x[2],Mk[2,1]*x[1]+Mk[2,2]*x[2]))
  return(x)
}
rprocess=discrete.time.sim(step.fun = oscilator.proc.sim, delta.t=1)

# Pomp object
oscilator=pomp(OscilatorData,times="Time",t0=1,rprocess=rprocess)

# Parameter initial guess and estimation.
theta <- c(omega=0.035,lambda=0.003,X.0 = matrix(c(1,0))) # el valor inicial solo puede ser
# un escalar???!
kf=enkf(oscilator, Np=10, R=R,h=h, params=theta)
```

**Comment by marius190** [comment]
Finally I was able to run enkf(). It worked defing names for the state initial process adding "statenames = c("xk","xk_1")" when calling to pomp.

**Comment by kingaa** [comment]
With reference to your first post, @marius190, I do not get the error you get when I run your code. I get

```
Error: in default 'initializer': there are no parameters with suffix '.0'. See '?pomp'.
```

Note there are a number of problems and misconceptions in your attempt. First of all, note that the error is not a **pomp** error: it results from an attempt to multiply two incommensurate matrices. Second, note that you are in several places making the assumption that **pomp** will handle matrices in some particular way. My guess is that you do not understand how **R** handles matrices. It's probably a good idea to learn the fundamentals of **R** before taking on something relatively sophisticated.

I spent a few minutes with your code. I recommend that you (1) study the following until you can understand what it is doing, and then (2) see if you think it is accomplishing what you are trying to accomplish. 

Note that I am using **pomp2**. For reasons described [here](https://kingaa.github.io/pomp/blog.html#pomp-version-2-released-as-pomp2), I recommend you use **pomp2** and not **pomp**.

```
### Non Harmonic oscillator example
## Deterministic latent state process,
## Normal measurement noise.
library(pomp2)

## Simulation
iter <- 100 # Data length
g <- 7 # sd of noise
omega <- 0.035
lambda <- 0.003
x <- matrix(nrow=iter,ncol=2)
y <- numeric(iter)
x[1,] <- c(1,0) #+rnorm(1,0,0.2)
y <- x[1,1]+rnorm(1,0,g)
dt <- 1:iter
for (i in 2:iter) {
  Mk <- c(2+omega^2-lambda^2*x[i-1,1]^2,1,-1,0)
  Mk <- matrix(Mk,nrow=2)
  x[i,] <- Mk%*%x[i-1,]
  y[i] <- x[i,1]+rnorm(1,0,g)
}

h <- function(x){c(1,0)%*%x}

R <- g

OscilatorData <- data.frame(Time=dt,Y=y)

# *Deterministic* X process
oscilator.proc.sim <- function (x1, x2, omega, lambda, delta.t, ...) {
  Mk <- matrix(
    c(2+omega*omega-lambda*lambda*x1*x1,1,-1,0),
    nrow=2,ncol=2
  )
  x <- Mk %*% c(x1,x2)
  setNames(x,c("x1","x2"))
}

theta <- c(omega=0.035,lambda=0.003,x1_0=1,x2_0=0)
## el valor inicial solo puede ser un escalar?
## Si, pero puede haber mas de uno.
kf <- enkf(OscilatorData,times="Time",t0=1, Np=2, R=R, h=h, params=theta,
  rprocess=discrete_time(step.fun = oscilator.proc.sim, delta.t=1))

## Note the value of Np.

plot(kf)
logLik(kf)

## is the filter mean identical to the simulation?
all(filter.mean(kf)==t(x))
```

**Comment by marius190** [comment]
Thanks for the answer.

Yes, the error you get is different, because I've made a change when defining X.0 on the web code. To get the same error, it is necesary to change X.0 = matrix(c(1,0)) as X.0=1 on the code.

Yes, the code implements the problem I want to accomplishing. About matrix I don't know exactly where I am supposing that pomp handle matrix in a particular way. I am using matrix multiplication when defining a vector function and no much more. About result I will answer the other post.
