### ISSUE TITLE
Issue with pomp pfilter [new]

### ISSUE THREAD

**Issue by natelee1019** [kingaa/pomp#87]
Hi all. I have been struggling for the following error for a few days.

Code as follows:

```
simulate(t0=0, times=1:50,
  params=c(r=exp(1),K=200,sigma=0.1,N_0=50,b=0.05),
  rinit=function (N_0, ...) {
    c(N=N_0)
  },
  rprocess=discrete_time(
    function (N, r, K, sigma, ...) {
      eps <- rnorm(n=1,mean=0,sd=sigma)
      c(N=r*N*exp(1-N/K+eps))
    },
    delta.t=1
  ),
  rmeasure=function (N, b, ...) {
    c(Y=rpois(n=1,lambda=b*N))
  }
)  -> r.sim

r_r=runif(10000,0,4)
r_sigma=runif(10000,0,0.5)
r_b=runif(10000,0,0.5)


Csnippet("
  lik = dpois(pop,b*N,give_log);
") -> dmeas

Csnippet("
  double eps = rnorm(0,sigma);
  N = r*N*exp(1-N/K+eps);
") -> rickstepC


Csnippet("
  pop = rpois(b*N);  
  ") -> rmeas

Csnippet("
  N = N_0;
  ") -> rinit

r.sim %>%
    pfilter(Np=1000,
      params=c(r=r_r[1],K=2000,sigma=r_sigma[1],N_0=1600,b=r_b[1]),
      rprocess=discrete_time(rickstepC,delta.t=1),
      rinit=rinit,
      rmeasure=rmeas,
      dmeasure=dmeas, paramnames=c("r","K","sigma","b","N_0")
      ,statenames=c("pop","N")) -> pfrick_1
```

I want to use the Pfilter function， and i follow most of the steps in https://kingaa.github.io/pomp/vignettes/getting_started.html#the_particle_filter.

My error message is saying : 
```
Error: in ‘pfilter’: error in building shared-object library from C snippets: in ‘Cbuilder’: compilation error: cannot compile shared-object library ‘C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.dll’: status = 1
compiler messages:
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c -o C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.o
C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c: In function '__pomp_rmeasure':
C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c:73:7: error: assignment of read-only location '*(__x + (sizetype)((long long unsigned int)*__stateindex * 8ull))'
   pop = rpois(b*N);  
       ^
make: *** [C:/PROGRA~1/R/R-35~1.2/etc/x64/Makeconf:208: C:/Users/Nat
In addition: Warning message:
In system2(command = R.home("bin/R"), args = c("CMD", "SHLIB", "-c",  :
  running command '"C:/PROGRA~1/R/R-35~1.2/bin/R" PKG_CPPFLAGS="-IC:/Users/Nate/Documents/R/win-library/3.5/pomp2/include -IC:/Users/Nate/Desktop" CMD SHLIB -c -o C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.dll C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c' had status 1
```

I think it is because i never specify the value of pop? I have checked 4.2 in http://kingaa.github.io/pomp/FAQ.html#why-cant-i-run-csnippets . It is working correctly. 

Can anyone please help？ Thank you!!

**Comment by natelee1019** [comment]
> Hi all. I have been struggling for the following error for a few days.
> 
> Code as follows:
> 
> simulate(t0=0, times=1:50,
> params=c(r=exp(1),K=200,sigma=0.1,N_0=50,b=0.05),
> rinit=function (N_0, ...) {
> c(N=N_0)
> },
> rprocess=discrete_time(
> function (N, r, K, sigma, ...) {
> eps <- rnorm(n=1,mean=0,sd=sigma)
> c(N=r_N_exp(1-N/K+eps))
> },
> delta.t=1
> ),
> rmeasure=function (N, b, ...) {
> c(Y=rpois(n=1,lambda=b*N))
> }
> ) -> r.sim
> 
> r_r=runif(10000,0,4)
> r_sigma=runif(10000,0,0.5)
> r_b=runif(10000,0,0.5)
> 
> Csnippet("
> lik = dpois(pop,b*N,give_log);
> ") -> dmeas
> 
> Csnippet("
> double eps = rnorm(0,sigma);
> N = r_N_exp(1-N/K+eps);
> ") -> rickstepC
> 
> Csnippet("
> pop = rpois(b*N);
> ") -> rmeas
> 
> Csnippet("
> N = N_0;
> ") -> rinit
> 
> r.sim %>%
> pfilter(Np=1000,
> params=c(r=r_r[1],K=2000,sigma=r_sigma[1],N_0=1600,b=r_b[1]),
> rprocess=discrete_time(rickstepC,delta.t=1),
> rinit=rinit,
> rmeasure=rmeas,
> dmeasure=dmeas, paramnames=c("r","K","sigma","b","N_0")
> ,statenames=c("pop","N")) -> pfrick_1
> 
> I want to use the Pfilter function， and i follow most of the steps in https://kingaa.github.io/pomp/vignettes/getting_started.html#the_particle_filter.
> 
> My error message is saying :
> Error: in ‘pfilter’: error in building shared-object library from C snippets: in ‘Cbuilder’: compilation error: cannot compile shared-object library ‘C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.dll’: status = 1
> compiler messages:
> c:/Rtools/mingw_64/bin/gcc -I"C:/PROGRA1/R/R-351.2/include" -DNDEBUG -O2 -Wall -std=gnu99 -mtune=generic -c C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c -o C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.o
> C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c: In function '__pomp_rmeasure':
> C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c:73:7: error: assignment of read-only location '_(__x + (sizetype)((long long unsigned int)___stateindex * 8ull))'
> pop = rpois(b*N);
> ^
> make: *** [C:/PROGRA1/R/R-351.2/etc/x64/Makeconf:208: C:/Users/Nat
> In addition: Warning message:
> In system2(command = R.home("bin/R"), args = c("CMD", "SHLIB", "-c", :
> running command '"C:/PROGRA1/R/R-351.2/bin/R" PKG_CPPFLAGS="-IC:/Users/Nate/Documents/R/win-library/3.5/pomp2/include -IC:/Users/Nate/Desktop" CMD SHLIB -c -o C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.dll C:/Users/Nate/AppData/Local/Temp/RtmpAtykVL/3220/pomp_92cdcf010f165aa88960a1f6caffc795.c' had status 1
> 
> I think it is because i never specify the value of pop? I have checked 4.2 in http://kingaa.github.io/pomp/FAQ.html#why-cant-i-run-csnippets . It is working correctly.
> 
> Can anyone please help？ Thank you!!

**Comment by natelee1019** [comment]
Also, I am able to get the result following steps in https://kingaa.github.io/pomp/vignettes/getting_started.html#the_particle_filter

**Comment by kingaa** [comment]
When you create the simulated data (in your call to `simulate`) the data are called `Y`.  In the particle filter calculation, the data are called `pop`, but there is no `pop` variable defined.  Just pick one name for the data, either `pop ` or `Y`.  For example:

```
library(pomp2)

simulate(t0=0, times=1:50,
  params=c(r=exp(1),K=200,sigma=0.1,N_0=50,b=0.05),
  rinit=function (N_0, ...) {
    c(N=N_0)
  },
  rprocess=discrete_time(
    function (N, r, K, sigma, ...) {
      eps <- rnorm(n=1,mean=0,sd=sigma)
      c(N=r*N*exp(1-N/K+eps))
    },
    delta.t=1
  ),
  rmeasure=function (N, b, ...) {
    c(Y=rpois(n=1,lambda=b*N))
  }
)  -> r.sim

r_r=runif(10000,0,4)
r_sigma=runif(10000,0,0.5)
r_b=runif(10000,0,0.5)

Csnippet("
  lik = dpois(Y,b*N,give_log);
  ") -> dmeas

Csnippet("
  double eps = rnorm(0,sigma);
  N = r*N*exp(1-N/K+eps);
  ") -> rickstepC


Csnippet("
  Y = rpois(b*N);  
  ") -> rmeas

Csnippet("
  N = N_0;
  ") -> rinit

r.sim %>%
  pfilter(Np=1000,
    params=c(r=r_r[1],K=2000,sigma=r_sigma[1],N_0=1600,b=r_b[1]),
    rprocess=discrete_time(rickstepC,delta.t=1),
    rinit=rinit,
    rmeasure=rmeas,
    dmeasure=dmeas, paramnames=c("r","K","sigma","b","N_0"),
    statenames=c("N")) -> pfrick_1
```

**Comment by natelee1019** [comment]
Thank you very much!
