### ISSUE TITLE
Problem with compiling C snippets on Windows

### ISSUE THREAD

**Issue by mc30** [kingaa/pomp#9]
I have a problem running pomp on my Windows (7, x64) machine. I have installed: pomp 1.2.2.1, R 3.2.3 and Rtools 3.3 (also tried 3.2).

Some of the C snippets do compile, but one of them doesn't. I get:
```
 fatal error: pomp.h: No such file or directory compilation terminated.
```
The problem is that I have
```
# include <pomp.h>
```
in this file instead of
```
 # include <C:/Users/***/Documents/R/win-library/3.2/pomp/include/pomp.h>
```
that I have for other generated .C files.

Any ideas why this might be happening?

**Comment by kingaa** [comment]
Hmm, interesting and strange that the failure occurs only for one Csnippet. Could you post the code that produces the error?

**Comment by mc30** [comment]
Here's the code:

```
sir_step <- Csnippet("
  double dN_SE = rbinom(S, 1 - exp(-Beta * I / N * dt));
  double dN_EI = rbinom(E, 1 - exp(-delta * dt));
  double dN_IR = rbinom(I, 1 - exp(-gamma * dt));
  S -= dN_SE;
  E += dN_SE - dN_EI;
  I += dN_EI - dN_IR;
  R += dN_IR;
  H += dN_IR;
")

sir_init <- Csnippet("
  S = N - 1;
  E = 0;
  I = 1;
  R = 0;
  H = 0;
")

pomp(sir, rprocess = euler.sim(sir_step, delta.t = 1), initializer = sir_init,
     paramnames = c("Beta", "gamma", "delta", "lag", "N"), statenames = c("S", "E", "I", "R", "H")) -> sir

pomp(sir, zeronames = "H") -> sir

dmeas <- Csnippet("lik = dbinom(Reported, H, rho, give_log);")
rmeas <- Csnippet("Reported = rbinom(H, rho);")

sir <- pomp(sir, rmeasure = rmeas, dmeasure = dmeas, statenames = "H", paramnames = "rho")

sims <- simulate(sir, params = c(Beta = 6.5, gamma = 1, delta = 1, lag = 10, rho = 0.5, N = 2500),
                 nsim = 1, as = TRUE, include = TRUE, internal = TRUE)
```

I get the error while trying to run the last command (i.e. inside simulate() function).

**Comment by kingaa** [comment]
Curiouser and curiouser...

The error doesn't show up when the codes are compiled, but when 'simulate' is run.  What is the error you get, precisely?  The error you mention in your original post must come during the compilation (i.e., in the call to 'pomp').  Have you tried re-running all the codes in a fresh session?

**Comment by mc30** [comment]
It seems to work now... All the generated .C files have the absolute path to "pomp.h". So I can't reproduce the error I used to get.

Thanks for your help anyway!
