### ISSUE TITLE
Assignment of model parameters to a pomp model

### ISSUE THREAD

**Issue by aakhmetz** [kingaa/pomp#91]
I observe a bit odd behavior with assigning model parameters to pomp-model. Precisely, when I change the model parameters directly by coef(pomp_model) = prmvalues, so that I have:
```
>>coef(pomp_model) = prmvalues
>>coef(pomp_model)
beta0
3.1
alpha1
0.02
alpha2
0.001
rho
0.6
phi
0.1
```
However, the values of model parameters from "fromEst" directory remains unchanged:
```
>>partrans(pomp_model, allpars, dir="fromEst")
beta0
22.1979512814416
alpha1
1.02020134002676
alpha2
1.00100050016671
rho
0.645656306225795
phi
0.52497918747894
```
In my opinion the latter should be updated and show the same values as the first command. Or is my understanding somehow wrong? 

I use the latest version of pomp2. Thank you in advance for taking a look.

**Comment by kingaa** [comment]
In your example, what is the relationship between the parameter vector `prmvalues` and `allpars`?  Also, what are the transformations you are using?  Without knowing these things, it's impossible to say whether this behavior is correct.  Can you provide the code for the transformations and the definitions of `prmvalues` and `allpars`?

**Comment by aakhmetz** [comment]
Dear Prof. King, It was my mistake in the coding which I found after some more investigation. Sorry for taking your time
