### ISSUE TITLE
Extracting traces from pmcmc object

### ISSUE THREAD

**Issue by fintzij** [kingaa/pomp#94]
Hello,

I am having difficulty extracting the posterior samples in a pmcmc object using the traces function. The error I am getting reads: 

Error: ‘traces’ is undefined for ‘object’ of class ‘pmcmc’. 

I've tried redefining the class of the pomp object to be of class 'pmcmcd_pomp', but get the same error that traces is undefined for an object of that class as well. I'm not sure how to extract samples manually either since the pmcmc object doesn't seem to have slot names. Querying the object using 'str' gives the following output:

Formal class 'pmcmc' [package "pomp"] with 0 slots
 Named list()

The samples are definitely in there though, since the pomp object showing up in my environment is several gigabytes in size. I'm just not quite sure how to get at them.

Thanks for your help!
Jon

**Comment by fintzij** [comment]
Quick followup: the model was fit using pomp version 1.18.Perhaps may have something to do with the problems I'm running into? I'd like to avoid refitting the model if possible. 

Thanks,
Jon

**Comment by fintzij** [comment]
Solution: installed pomp version 1.16 and was able to use the now-deprecated 'conv.rec' function to get at the posterior samples. Closing the issue.

**Comment by kingaa** [comment]
Your solution is really a postponement of the problem.  Obviously, it would be better from a number of perspectives to install the latest version and use the `traces` function.

**Comment by fintzij** [comment]
Agreed!
