### ISSUE TITLE
Parallelized trajectory matching in Pomp2?

### ISSUE THREAD

**Issue by beansrowning** [kingaa/pomp#96]
I've been working with parameter estimation and can't seem to get parallelized code working that used to work pre-version 2

I'm using Win 10 with doParallel and tried on two different machines and different R versions (3.5.3, 3.6.0), to no avail.

Hard to make a simple reprex, but I'm actually working on retrofitting [your SEIR model](https://doi.org/10.5061/dryad.r5f30) from the West African outbreak to the current DRC outbreak and bringing the code up to the new syntax in the process.

The R0 trajectory matching looks something like this (which will no doubt look familiar to you):

```R
profR0 <- bake(file = "output/R0_fits.rds", {

  starts <- profileDesign(
    R0 = seq(1, 3, length = 200),
    upper = c(k = 1),
    lower = c(k = 1e-8),
    nprof = 40
  )

  out <- foreach(
    start = iter(starts, by = "row"),
    .combine = rbind,
    .inorder = FALSE
    ) %:%
    foreach(
      type = c("raw", "cum"),
      .combine = rbind,
      .inorder = FALSE,
      .packages = c("pomp", "subplex")
      ) %dopar% {

      tm <- models[[type]]

      tic <- Sys.time()
      
      coef(tm, names(start)) <- unname(unlist(start))

      coef(tm, "rho") <- 0.2

      tm <- traj_objfun(
        tm,
        est = c("k", "E_0", "I_0")
      )

      if (coef(tm, "k") == 0) {
        coef(tm, "k") <- 1e-8
      } 
      if (coef(tm, "E_0") == 0) {
        coef(tm, "E_0") <- 1e-12
      } 
      if (coef(tm, "I_0") == 0) {
        coef(tm,"I_0") <- 1e-12
      }

      tm_optim <- subplex(
        fn = tm,
        par = coef(tm, c("k", "E_0", "I_0")),
        control = list(maxit = 1e5)
      )

      toc <- Sys.time()

      # Compute system time
      etime <- toc - tic
      
      units(etime) <- "hours"
      
      data.frame(
        country = "DRC",
        type = type,
        as.list(coef(tm)),
        loglik = logLik(tm),
        conv = tm_optim$convergence,
        etime = as.numeric(etime)
      )
      } 
      
  # Final transformation
  out <- out %>% mutate(
    sum = S_0 + E_0 + I_0 + R_0,
    S_0 = round(N * S_0 / sum),
    E_0 = round(N * E_0 / sum),
    I_0 = round(N * I_0 / sum),
    R_0 = round(N * R_0 / sum)
  ) %>%
  filter(conv %in% 0:1) %>%
  select(-sum) %>%
  distinct()

  out
})
```  

Setting the parallel back-end to sequential, this runs to completion.
With any number of parallel workers, R throws the following error:

```
Error in { :
  task 1 failed - "in 'traj_objfun': in 'partrans': unable to load shared object 'C:/Users/<user>/AppData/Local/Temp/1/RtmpUHhrmA/15168/pomp_2504fac78c13ec90ca2aa55dfaf49846.dll':
  LoadLibrary failure:  The specified module could not be found.
"
```  

Navigating to this path though, I can confirm that the dll does exist and is loadable.

I guess I'm wondering if this is now a new limitation in pomp2 where multiple R workers may fail to load a shared library concurrently, or if I'm making a boneheaded error. 

I perused the documentation and tried looking for some more recent examples and seem to have come up short.

**Comment by kingaa** [comment]
Not sure just what is happening, but recent versions of Windows have been having trouble building and loading C snippet files in parallel.  I suspect this is due to aggressive Windows security features. 

Try setting the `cdir` and/or `cfile` arguments in the call that constructs `models`.  The problem I've seen is consistent with Windows objecting to creating a file in the temporary directory and then compiling it.  With `cdir`, you can choose to put the C snippet files in another directory (say the current working directory (`getwd()`)).  By default, a random name is given to the C snippet file; you can change this behavior by specifying the target name in `cfile`.

Please let me know if this solves the problem.

**Comment by beansrowning** [comment]
Looks like setting `cdir` to different temporary folder seemed to fix it.

I'll test it out on a few different machines to make sure that's working universally. 


Thanks for the quick response!

**Comment by kingaa** [comment]
@beansrowning:

It would be great if you could send along any more information you have about the failure.  As I say, a number of windows 10 users have run into what appears to be the same problem, and I'd like to add it to the FAQ.  You can help to make that as useful as possible!

Also, please note that the latest release (2.2.2, available, in source and binary, on github only) fixes a bug that won't arise in your case, but can lead to segfaults when the `cfile` argument is reused.

**Comment by kingaa** [comment]
I will close this issue now, but please feel free to reopen if more discussion is warranted.

**Comment by beansrowning** [comment]
Sounds good.

I've been slammed lately, but when I get some time I'd be happy to help add to the FAQs!

I appreciate all of your help.
